/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const avatarGroupInjectionKey: typeof import('../src/runtime/composables/useAvatarGroup')['avatarGroupInjectionKey']
  const buttonGroupInjectionKey: typeof import('../src/runtime/composables/useButtonGroup')['buttonGroupInjectionKey']
  const defineLocale: typeof import('../src/runtime/composables/defineLocale')['defineLocale']
  const defineShortcuts: typeof import('../src/runtime/composables/defineShortcuts')['defineShortcuts']
  const extractShortcuts: typeof import('../src/runtime/composables/defineShortcuts')['extractShortcuts']
  const formBusInjectionKey: typeof import('../src/runtime/composables/useFormField')['formBusInjectionKey']
  const formFieldInjectionKey: typeof import('../src/runtime/composables/useFormField')['formFieldInjectionKey']
  const formInputsInjectionKey: typeof import('../src/runtime/composables/useFormField')['formInputsInjectionKey']
  const formLoadingInjectionKey: typeof import('../src/runtime/composables/useFormField')['formLoadingInjectionKey']
  const formOptionsInjectionKey: typeof import('../src/runtime/composables/useFormField')['formOptionsInjectionKey']
  const inputIdInjectionKey: typeof import('../src/runtime/composables/useFormField')['inputIdInjectionKey']
  const kbdKeysMap: typeof import('../src/runtime/composables/useKbd')['kbdKeysMap']
  const localeContextInjectionKey: typeof import('../src/runtime/composables/useLocale')['localeContextInjectionKey']
  const useAppConfig: typeof import('../src/runtime/vue/composables/useAppConfig')['useAppConfig']
  const useAvatarGroup: typeof import('../src/runtime/composables/useAvatarGroup')['useAvatarGroup']
  const useButtonGroup: typeof import('../src/runtime/composables/useButtonGroup')['useButtonGroup']
  const useComponentIcons: typeof import('../src/runtime/composables/useComponentIcons')['useComponentIcons']
  const useFormField: typeof import('../src/runtime/composables/useFormField')['useFormField']
  const useKbd: typeof import('../src/runtime/composables/useKbd')['useKbd']
  const useLocale: typeof import('../src/runtime/composables/useLocale')['useLocale']
  const useOverlay: typeof import('../src/runtime/composables/useOverlay')['useOverlay']
  const useToast: typeof import('../src/runtime/composables/useToast')['useToast']
}
// for type re-export
declare global {
  // @ts-ignore
  export type { ShortcutConfig, ShortcutsConfig, ShortcutsOptions } from '../src/runtime/composables/defineShortcuts'
  import('../src/runtime/composables/defineShortcuts')
  // @ts-ignore
  export type { UseComponentIconsProps } from '../src/runtime/composables/useComponentIcons'
  import('../src/runtime/composables/useComponentIcons')
  // @ts-ignore
  export type { KbdKey, KbdKeySpecific } from '../src/runtime/composables/useKbd'
  import('../src/runtime/composables/useKbd')
  // @ts-ignore
  export type { OverlayOptions, Overlay } from '../src/runtime/composables/useOverlay'
  import('../src/runtime/composables/useOverlay')
  // @ts-ignore
  export type { Toast } from '../src/runtime/composables/useToast'
  import('../src/runtime/composables/useToast')
}
