packages:
  - ./
  - cli
  - docs
  - playgrounds/nuxt
  - playgrounds/vue
  - playgrounds/repl

ignoreWorkspaceRootCheck: true

linkWorkspacePackages: true

overrides:
  '@nuxt/kit': ^4.4.8
  '@nuxt/test-utils': 4.0.2
  '@nuxt/ui': workspace:*
  unplugin: ^3.2.0
  c12: ^3.3.4
  h3: 1.15.11
  typescript: ^6.0.3

allowBuilds:
  better-sqlite3: true
  puppeteer: true
  sharp: true
  '@parcel/watcher': false
  '@tailwindcss/oxide': false
  '@vercel/speed-insights': false
  esbuild: false
  unrs-resolver: false
  vue-demi: false

minimumReleaseAgeExclude:
  - '@ai-sdk/anthropic@4.0.0'
  - '@ai-sdk/gateway@4.0.0'
  - '@ai-sdk/mcp@2.0.0'
  - '@ai-sdk/provider-utils@5.0.0'
  - '@ai-sdk/provider@4.0.0'
  - '@ai-sdk/vue@4.0.0'
  - '@nuxt/icon@2.2.5'
  - ai@7.0.0
