import lucide from '../../../../src/theme/icons'

// Picking a set replaces appConfig.ui.icons wholesale, so every set must
// map the full key list from src/theme/icons, a missing key would blank
// that icon across the whole app. Names are validated against the Iconify
// API (sets beyond lucide resolve through @nuxt/icon's API fallback).
export const themeIcons = {
  lucide,
  bootstrap: {
    arrowDown: 'i-bi-arrow-down',
    arrowLeft: 'i-bi-arrow-left',
    arrowRight: 'i-bi-arrow-right',
    arrowUp: 'i-bi-arrow-up',
    caution: 'i-bi-exclamation-circle',
    check: 'i-bi-check',
    chevronDoubleLeft: 'i-bi-chevron-double-left',
    chevronDoubleRight: 'i-bi-chevron-double-right',
    chevronDown: 'i-bi-chevron-down',
    chevronLeft: 'i-bi-chevron-left',
    chevronRight: 'i-bi-chevron-right',
    chevronUp: 'i-bi-chevron-up',
    close: 'i-bi-x',
    copy: 'i-bi-clipboard',
    copyCheck: 'i-bi-clipboard-check',
    dark: 'i-bi-moon',
    drag: 'i-bi-grip-vertical',
    ellipsis: 'i-bi-three-dots',
    error: 'i-bi-x-circle',
    external: 'i-bi-box-arrow-up-right',
    eye: 'i-bi-eye',
    eyeOff: 'i-bi-eye-slash',
    file: 'i-bi-file-earmark',
    folder: 'i-bi-folder',
    folderOpen: 'i-bi-folder2-open',
    hash: 'i-bi-hash',
    info: 'i-bi-info-circle',
    light: 'i-bi-sun',
    loading: 'i-bi-arrow-repeat',
    menu: 'i-bi-list',
    minus: 'i-bi-dash',
    panelClose: 'i-bi-arrow-bar-left',
    panelOpen: 'i-bi-arrow-bar-right',
    plus: 'i-bi-plus',
    reload: 'i-bi-arrow-counterclockwise',
    search: 'i-bi-search',
    stop: 'i-bi-square',
    star: 'i-bi-star',
    success: 'i-bi-check-circle',
    system: 'i-bi-display',
    tip: 'i-bi-lightbulb',
    upload: 'i-bi-upload',
    warning: 'i-bi-exclamation-triangle'
  },
  heroicons: {
    arrowDown: 'i-heroicons-arrow-down',
    arrowLeft: 'i-heroicons-arrow-left',
    arrowRight: 'i-heroicons-arrow-right',
    arrowUp: 'i-heroicons-arrow-up',
    caution: 'i-heroicons-exclamation-circle',
    check: 'i-heroicons-check',
    chevronDoubleLeft: 'i-heroicons-chevron-double-left',
    chevronDoubleRight: 'i-heroicons-chevron-double-right',
    chevronDown: 'i-heroicons-chevron-down',
    chevronLeft: 'i-heroicons-chevron-left',
    chevronRight: 'i-heroicons-chevron-right',
    chevronUp: 'i-heroicons-chevron-up',
    close: 'i-heroicons-x-mark',
    copy: 'i-heroicons-clipboard',
    copyCheck: 'i-heroicons-clipboard-document-check',
    dark: 'i-heroicons-moon',
    drag: 'i-heroicons-bars-3',
    ellipsis: 'i-heroicons-ellipsis-horizontal',
    error: 'i-heroicons-x-circle',
    external: 'i-heroicons-arrow-up-right',
    eye: 'i-heroicons-eye',
    eyeOff: 'i-heroicons-eye-slash',
    file: 'i-heroicons-document',
    folder: 'i-heroicons-folder',
    folderOpen: 'i-heroicons-folder-open',
    hash: 'i-heroicons-hashtag',
    info: 'i-heroicons-information-circle',
    light: 'i-heroicons-sun',
    loading: 'i-heroicons-arrow-path',
    menu: 'i-heroicons-bars-3',
    minus: 'i-heroicons-minus',
    panelClose: 'i-heroicons-chevron-left',
    panelOpen: 'i-heroicons-chevron-right',
    plus: 'i-heroicons-plus',
    reload: 'i-heroicons-arrow-uturn-left',
    search: 'i-heroicons-magnifying-glass',
    stop: 'i-heroicons-stop',
    star: 'i-heroicons-star',
    success: 'i-heroicons-check-circle',
    system: 'i-heroicons-computer-desktop',
    tip: 'i-heroicons-light-bulb',
    upload: 'i-heroicons-arrow-up-tray',
    warning: 'i-heroicons-exclamation-triangle'
  },
  iconoir: {
    arrowDown: 'i-iconoir-arrow-down',
    arrowLeft: 'i-iconoir-arrow-left',
    arrowRight: 'i-iconoir-arrow-right',
    arrowUp: 'i-iconoir-arrow-up',
    caution: 'i-iconoir-warning-circle',
    check: 'i-iconoir-check',
    chevronDoubleLeft: 'i-iconoir-fast-arrow-left',
    chevronDoubleRight: 'i-iconoir-fast-arrow-right',
    chevronDown: 'i-iconoir-nav-arrow-down',
    chevronLeft: 'i-iconoir-nav-arrow-left',
    chevronRight: 'i-iconoir-nav-arrow-right',
    chevronUp: 'i-iconoir-nav-arrow-up',
    close: 'i-iconoir-xmark',
    copy: 'i-iconoir-copy',
    copyCheck: 'i-iconoir-clipboard-check',
    dark: 'i-iconoir-half-moon',
    drag: 'i-iconoir-menu',
    ellipsis: 'i-iconoir-more-horiz',
    error: 'i-iconoir-xmark-circle',
    external: 'i-iconoir-arrow-up-right',
    eye: 'i-iconoir-eye',
    eyeOff: 'i-iconoir-eye-closed',
    file: 'i-iconoir-page',
    folder: 'i-iconoir-folder',
    // iconoir has no open-folder glyph, repeat the closed folder rather
    // than show a book on expanded tree nodes
    folderOpen: 'i-iconoir-folder',
    hash: 'i-iconoir-hashtag',
    info: 'i-iconoir-info-circle',
    light: 'i-iconoir-sun-light',
    loading: 'i-iconoir-refresh',
    menu: 'i-iconoir-menu',
    minus: 'i-iconoir-minus',
    panelClose: 'i-iconoir-sidebar-collapse',
    panelOpen: 'i-iconoir-sidebar-expand',
    plus: 'i-iconoir-plus',
    reload: 'i-iconoir-undo',
    search: 'i-iconoir-search',
    stop: 'i-iconoir-square',
    star: 'i-iconoir-star',
    success: 'i-iconoir-check-circle',
    system: 'i-iconoir-computer',
    tip: 'i-iconoir-light-bulb',
    upload: 'i-iconoir-upload',
    warning: 'i-iconoir-warning-triangle'
  },
  material: {
    arrowDown: 'i-material-symbols-arrow-downward-rounded',
    arrowLeft: 'i-material-symbols-arrow-back-rounded',
    arrowRight: 'i-material-symbols-arrow-forward-rounded',
    arrowUp: 'i-material-symbols-arrow-upward-rounded',
    caution: 'i-material-symbols-error-outline-rounded',
    check: 'i-material-symbols-check-rounded',
    chevronDoubleLeft: 'i-material-symbols-keyboard-double-arrow-left-rounded',
    chevronDoubleRight: 'i-material-symbols-keyboard-double-arrow-right-rounded',
    chevronDown: 'i-material-symbols-keyboard-arrow-down-rounded',
    chevronLeft: 'i-material-symbols-chevron-left-rounded',
    chevronRight: 'i-material-symbols-chevron-right-rounded',
    chevronUp: 'i-material-symbols-keyboard-arrow-up-rounded',
    close: 'i-material-symbols-close-rounded',
    copy: 'i-material-symbols-content-copy-outline-rounded',
    copyCheck: 'i-material-symbols-inventory-rounded',
    dark: 'i-material-symbols-dark-mode-outline-rounded',
    drag: 'i-material-symbols-drag-indicator',
    ellipsis: 'i-material-symbols-more-horiz',
    error: 'i-material-symbols-cancel-outline-rounded',
    external: 'i-material-symbols-arrow-outward-rounded',
    eye: 'i-material-symbols-visibility-outline-rounded',
    eyeOff: 'i-material-symbols-visibility-off-outline-rounded',
    file: 'i-material-symbols-description-outline-rounded',
    folder: 'i-material-symbols-folder-outline-rounded',
    folderOpen: 'i-material-symbols-folder-open-outline-rounded',
    hash: 'i-material-symbols-tag-rounded',
    info: 'i-material-symbols-info-outline-rounded',
    // colon form: the dashed name would resolve against the separate
    // material-symbols-light collection and never load
    light: 'i-material-symbols:light-mode-outline-rounded',
    loading: 'i-material-symbols-progress-activity',
    menu: 'i-material-symbols-menu-rounded',
    minus: 'i-material-symbols-remove-rounded',
    panelClose: 'i-material-symbols-left-panel-close-outline-rounded',
    panelOpen: 'i-material-symbols-left-panel-open-outline-rounded',
    plus: 'i-material-symbols-add-rounded',
    reload: 'i-material-symbols-refresh-rounded',
    search: 'i-material-symbols-search-rounded',
    stop: 'i-material-symbols-stop-outline-rounded',
    star: 'i-material-symbols-star-outline-rounded',
    success: 'i-material-symbols-check-circle-outline-rounded',
    system: 'i-material-symbols-desktop-windows-outline-rounded',
    tip: 'i-material-symbols-lightbulb-outline-rounded',
    upload: 'i-material-symbols-upload-rounded',
    warning: 'i-material-symbols-warning-outline-rounded'
  },
  phosphor: {
    arrowDown: 'i-ph-arrow-down',
    arrowLeft: 'i-ph-arrow-left',
    arrowRight: 'i-ph-arrow-right',
    arrowUp: 'i-ph-arrow-up',
    caution: 'i-ph-warning-circle',
    check: 'i-ph-check',
    chevronDoubleLeft: 'i-ph-caret-double-left',
    chevronDoubleRight: 'i-ph-caret-double-right',
    chevronDown: 'i-ph-caret-down',
    chevronLeft: 'i-ph-caret-left',
    chevronRight: 'i-ph-caret-right',
    chevronUp: 'i-ph-caret-up',
    close: 'i-ph-x',
    copy: 'i-ph-copy',
    copyCheck: 'i-ph-check-circle',
    dark: 'i-ph-moon',
    drag: 'i-ph-dots-six-vertical',
    ellipsis: 'i-ph-dots-three',
    error: 'i-ph-x-circle',
    external: 'i-ph-arrow-up-right',
    eye: 'i-ph-eye',
    eyeOff: 'i-ph-eye-slash',
    file: 'i-ph-file',
    folder: 'i-ph-folder',
    folderOpen: 'i-ph-folder-open',
    hash: 'i-ph-hash',
    info: 'i-ph-info',
    light: 'i-ph-sun',
    loading: 'i-ph-circle-notch',
    menu: 'i-ph-list',
    minus: 'i-ph-minus',
    panelClose: 'i-ph-caret-left',
    panelOpen: 'i-ph-caret-right',
    plus: 'i-ph-plus',
    reload: 'i-ph-arrow-counter-clockwise',
    search: 'i-ph-magnifying-glass',
    stop: 'i-ph-square',
    star: 'i-ph-star',
    success: 'i-ph-check-circle',
    system: 'i-ph-monitor',
    tip: 'i-ph-lightbulb',
    upload: 'i-ph-upload',
    warning: 'i-ph-warning'
  },
  remix: {
    arrowDown: 'i-ri-arrow-down-line',
    arrowLeft: 'i-ri-arrow-left-line',
    arrowRight: 'i-ri-arrow-right-line',
    arrowUp: 'i-ri-arrow-up-line',
    caution: 'i-ri-error-warning-line',
    check: 'i-ri-check-line',
    chevronDoubleLeft: 'i-ri-arrow-left-double-line',
    chevronDoubleRight: 'i-ri-arrow-right-double-line',
    chevronDown: 'i-ri-arrow-down-s-line',
    chevronLeft: 'i-ri-arrow-left-s-line',
    chevronRight: 'i-ri-arrow-right-s-line',
    chevronUp: 'i-ri-arrow-up-s-line',
    close: 'i-ri-close-line',
    copy: 'i-ri-file-copy-line',
    copyCheck: 'i-ri-checkbox-multiple-line',
    dark: 'i-ri-moon-line',
    drag: 'i-ri-draggable',
    ellipsis: 'i-ri-more-line',
    error: 'i-ri-close-circle-line',
    external: 'i-ri-external-link-line',
    eye: 'i-ri-eye-line',
    eyeOff: 'i-ri-eye-off-line',
    file: 'i-ri-file-line',
    folder: 'i-ri-folder-line',
    folderOpen: 'i-ri-folder-open-line',
    hash: 'i-ri-hashtag',
    info: 'i-ri-information-line',
    light: 'i-ri-sun-line',
    loading: 'i-ri-loader-4-line',
    menu: 'i-ri-menu-line',
    minus: 'i-ri-subtract-line',
    panelClose: 'i-ri-sidebar-fold-line',
    panelOpen: 'i-ri-sidebar-unfold-line',
    plus: 'i-ri-add-line',
    reload: 'i-ri-arrow-go-back-line',
    search: 'i-ri-search-line',
    stop: 'i-ri-stop-line',
    star: 'i-ri-star-line',
    success: 'i-ri-checkbox-circle-line',
    system: 'i-ri-computer-line',
    tip: 'i-ri-lightbulb-line',
    upload: 'i-ri-upload-2-line',
    warning: 'i-ri-alert-line'
  },
  tabler: {
    arrowDown: 'i-tabler-arrow-down',
    arrowLeft: 'i-tabler-arrow-left',
    arrowRight: 'i-tabler-arrow-right',
    arrowUp: 'i-tabler-arrow-up',
    caution: 'i-tabler-alert-square-rounded',
    check: 'i-tabler-check',
    chevronDoubleLeft: 'i-tabler-chevrons-left',
    chevronDoubleRight: 'i-tabler-chevrons-right',
    chevronDown: 'i-tabler-chevron-down',
    chevronLeft: 'i-tabler-chevron-left',
    chevronRight: 'i-tabler-chevron-right',
    chevronUp: 'i-tabler-chevron-up',
    close: 'i-tabler-x',
    copy: 'i-tabler-copy',
    copyCheck: 'i-tabler-copy-check',
    dark: 'i-tabler-moon',
    drag: 'i-tabler-grip-vertical',
    ellipsis: 'i-tabler-dots',
    error: 'i-tabler-square-rounded-x',
    external: 'i-tabler-external-link',
    eye: 'i-tabler-eye',
    eyeOff: 'i-tabler-eye-off',
    file: 'i-tabler-file',
    folder: 'i-tabler-folder',
    folderOpen: 'i-tabler-folder-open',
    hash: 'i-tabler-hash',
    info: 'i-tabler-info-square-rounded',
    light: 'i-tabler-sun',
    loading: 'i-tabler-loader-2',
    menu: 'i-tabler-menu',
    minus: 'i-tabler-minus',
    panelClose: 'i-tabler-layout-sidebar-left-collapse',
    panelOpen: 'i-tabler-layout-sidebar-left-expand',
    plus: 'i-tabler-plus',
    reload: 'i-tabler-reload',
    search: 'i-tabler-search',
    stop: 'i-tabler-player-stop',
    star: 'i-tabler-star',
    success: 'i-tabler-square-rounded-check',
    system: 'i-tabler-device-desktop',
    tip: 'i-tabler-bulb',
    upload: 'i-tabler-upload',
    warning: 'i-tabler-alert-triangle'
  },
  // 8-bit pixel-art set for the Comic preset. Pixelarticons is a functional
  // UI pack (unlike streamline-pixel, which has no arrows/chevrons), but it
  // still lacks a few glyphs, noted inline where a substitute stands in.
  pixelarticons: {
    arrowDown: 'i-pixelarticons-arrow-down',
    arrowLeft: 'i-pixelarticons-arrow-left',
    arrowRight: 'i-pixelarticons-arrow-right',
    arrowUp: 'i-pixelarticons-arrow-up',
    caution: 'i-pixelarticons-square-alert',
    check: 'i-pixelarticons-check',
    // No double-chevron glyph, single directional chevrons keep prev/next
    // (pagination first/last, calendar year nav) pointing the right way.
    chevronDoubleLeft: 'i-pixelarticons-chevron-left',
    chevronDoubleRight: 'i-pixelarticons-chevron-right',
    chevronDown: 'i-pixelarticons-chevron-down',
    chevronLeft: 'i-pixelarticons-chevron-left',
    chevronRight: 'i-pixelarticons-chevron-right',
    chevronUp: 'i-pixelarticons-chevron-up',
    close: 'i-pixelarticons-close',
    copy: 'i-pixelarticons-clipboard',
    copyCheck: 'i-pixelarticons-clipboard-note',
    dark: 'i-pixelarticons-moon',
    // No grip/drag handle, vertical dots read as a draggable affordance.
    drag: 'i-pixelarticons-more-vertical',
    ellipsis: 'i-pixelarticons-more-horizontal',
    error: 'i-pixelarticons-letter-x-circle',
    external: 'i-pixelarticons-external-link',
    eye: 'i-pixelarticons-eye',
    eyeOff: 'i-pixelarticons-eye-off',
    file: 'i-pixelarticons-file',
    // No open-folder glyph, repeat the closed folder (as iconoir does).
    folder: 'i-pixelarticons-folder',
    folderOpen: 'i-pixelarticons-folder',
    hash: 'i-pixelarticons-hash',
    info: 'i-pixelarticons-info-box',
    light: 'i-pixelarticons-sun',
    loading: 'i-pixelarticons-loader',
    menu: 'i-pixelarticons-menu',
    minus: 'i-pixelarticons-minus',
    panelClose: 'i-pixelarticons-chevron-left',
    panelOpen: 'i-pixelarticons-chevron-right',
    plus: 'i-pixelarticons-plus',
    reload: 'i-pixelarticons-reload',
    search: 'i-pixelarticons-search',
    // No dedicated stop glyph, a filled square is the universal stop mark.
    stop: 'i-pixelarticons-square',
    star: 'i-pixelarticons-star',
    success: 'i-pixelarticons-check',
    system: 'i-pixelarticons-monitor',
    tip: 'i-pixelarticons-lightbulb',
    upload: 'i-pixelarticons-upload',
    warning: 'i-pixelarticons-warning-diamond'
  }
}

export type ThemeIcons = keyof typeof themeIcons

/**
 * A short strip of a set's own glyphs, for previewing it in a picker row,
 * these eight differ enough between packs to tell them apart at a glance.
 */
export function iconSetSamples(setName: string): string[] {
  const set = (themeIcons as Record<string, Record<string, string>>)[setName] || {}
  return ['search', 'check', 'warning', 'light', 'dark', 'star', 'folder', 'upload']
    .map(key => set[key])
    .filter((name): name is string => !!name)
}

/**
 * Glyphs for the studio's own chrome (toolbar controls, the header Ask-AI
 * button, the theme-picker/preset button), per icon pack, so the chrome skins
 * to match the applied theme. Kept OUT of `themeIcons` on purpose: these are
 * studio-only and must never ride the export's icon config. `reset` is its own
 * circular-arrow glyph rather than reusing the `reload` semantic key, in
 * several packs `reload` is a back-arrow that would collide with `undo`.
 * Import and the group-picker chevron reuse the standard `upload`/`chevronDown`
 * keys (present in every pack), so they aren't repeated here.
 */
export const studioIcons: Record<ThemeIcons, {
  undo: string
  redo: string
  reset: string
  export: string
  /** Header "Ask AI" button. */
  assistant: string
  /** Theme-picker + preset-menu button. */
  themes: string
  /** The studio toolbar's Options panel trigger. */
  options: string
  /** The studio toolbar's Text panel trigger. */
  text: string
  /** The studio toolbar's Radius trigger. */
  radius: string
  /** Preset-menu randomize die. Packs without a die use their shuffle glyph. */
  dice: string
}> = {
  lucide: { undo: 'i-lucide-undo-2', redo: 'i-lucide-redo-2', reset: 'i-lucide-rotate-ccw', export: 'i-lucide-code-xml', assistant: 'i-lucide-bot-message-square', themes: 'i-lucide-swatch-book', options: 'i-lucide-sliders-horizontal', text: 'i-lucide-type', radius: 'i-lucide-square-round-corner', dice: 'i-lucide-dices' },
  bootstrap: { undo: 'i-bi-arrow-90deg-left', redo: 'i-bi-arrow-90deg-right', reset: 'i-bi-arrow-counterclockwise', export: 'i-bi-code-slash', assistant: 'i-bi-robot', themes: 'i-bi-palette', options: 'i-bi-sliders', text: 'i-bi-fonts', radius: 'i-bi-bounding-box', dice: 'i-bi-dice-5' },
  heroicons: { undo: 'i-heroicons-arrow-uturn-left', redo: 'i-heroicons-arrow-uturn-right', reset: 'i-heroicons-arrow-path', export: 'i-heroicons-code-bracket', assistant: 'i-heroicons-sparkles', themes: 'i-heroicons-swatch', options: 'i-heroicons-adjustments-horizontal', text: 'i-heroicons-language', radius: 'i-heroicons-stop', dice: 'i-heroicons-arrows-right-left' },
  iconoir: { undo: 'i-iconoir-undo', redo: 'i-iconoir-redo', reset: 'i-iconoir-refresh-double', export: 'i-iconoir-code', assistant: 'i-iconoir-magic-wand', themes: 'i-iconoir-palette', options: 'i-iconoir-settings', text: 'i-iconoir-text', radius: 'i-iconoir-square', dice: 'i-iconoir-shuffle' },
  material: { undo: 'i-material-symbols-undo', redo: 'i-material-symbols-redo', reset: 'i-material-symbols-refresh', export: 'i-material-symbols-code', assistant: 'i-material-symbols-robot', themes: 'i-material-symbols-palette', options: 'i-material-symbols-tune', text: 'i-material-symbols-text-fields', radius: 'i-material-symbols-rounded-corner', dice: 'i-material-symbols-shuffle' },
  phosphor: { undo: 'i-ph-arrow-arc-left', redo: 'i-ph-arrow-arc-right', reset: 'i-ph-arrow-counter-clockwise', export: 'i-ph-code', assistant: 'i-ph-robot', themes: 'i-ph-palette', options: 'i-ph-sliders-horizontal', text: 'i-ph-text-aa', radius: 'i-ph-square', dice: 'i-ph-shuffle' },
  remix: { undo: 'i-ri-arrow-go-back-line', redo: 'i-ri-arrow-go-forward-line', reset: 'i-ri-restart-line', export: 'i-ri-code-s-slash-line', assistant: 'i-ri-robot-2-line', themes: 'i-ri-palette-line', options: 'i-ri-equalizer-line', text: 'i-ri-font-size', radius: 'i-ri-rounded-corner', dice: 'i-ri-dice-line' },
  tabler: { undo: 'i-tabler-arrow-back-up', redo: 'i-tabler-arrow-forward-up', reset: 'i-tabler-refresh', export: 'i-tabler-code', assistant: 'i-tabler-robot', themes: 'i-tabler-palette', options: 'i-tabler-adjustments-horizontal', text: 'i-tabler-typography', radius: 'i-tabler-border-radius', dice: 'i-tabler-dice' },
  // Pixel pack has no `themes`/`palette` glyph, so `colors-swatch` stands in
  // for the swatch-book.
  pixelarticons: { undo: 'i-pixelarticons-undo', redo: 'i-pixelarticons-redo', reset: 'i-pixelarticons-reload', export: 'i-pixelarticons-code', assistant: 'i-pixelarticons-robot', themes: 'i-pixelarticons-colors-swatch', options: 'i-pixelarticons-sliders', text: 'i-pixelarticons-text-add', radius: 'i-pixelarticons-card', dice: 'i-pixelarticons-dice' }
}

/**
 * Functional icons the preview demos use beyond the 43 semantic keys (dashboard
 * nav, account menus, etc.). These are NOT part of any theme, they only skin
 * the studio's demo content to the applied pack, so they stay out of themeIcons
 * (and exports). The Lucide names ARE the defaults each demo already hardcodes;
 * `studioExtraOverrides` supplies a pack's glyph where it differs, falling back
 * to the Lucide default for any pack/key with no entry.
 */
export const STUDIO_EXTRA_DEFAULTS = {
  bell: 'i-lucide-bell',
  calendar: 'i-lucide-calendar',
  settings: 'i-lucide-settings',
  home: 'i-lucide-house',
  inbox: 'i-lucide-inbox',
  logout: 'i-lucide-log-out',
  trash: 'i-lucide-trash',
  user: 'i-lucide-user',
  users: 'i-lucide-users',
  userPlus: 'i-lucide-user-plus',
  send: 'i-lucide-send',
  reply: 'i-lucide-reply',
  paperclip: 'i-lucide-paperclip',
  messageCircle: 'i-lucide-message-circle',
  creditCard: 'i-lucide-credit-card',
  dollar: 'i-lucide-circle-dollar-sign',
  cart: 'i-lucide-shopping-cart',
  chart: 'i-lucide-chart-pie',
  list: 'i-lucide-list',
  sort: 'i-lucide-chevrons-up-down',
  mail: 'i-lucide-mail',
  heart: 'i-lucide-heart',
  github: 'i-lucide-github',
  trendingUp: 'i-lucide-trending-up',
  trendingDown: 'i-lucide-trending-down',
  tag: 'i-lucide-tag',
  filePlus: 'i-lucide-file-plus',
  folderPlus: 'i-lucide-folder-plus',
  movie: 'i-lucide-clapperboard',
  clock: 'i-lucide-clock',
  coffee: 'i-lucide-coffee',
  globe: 'i-lucide-globe',
  share: 'i-lucide-share',
  link: 'i-lucide-link',
  lock: 'i-lucide-lock',
  filter: 'i-lucide-filter',
  image: 'i-lucide-image',
  camera: 'i-lucide-camera',
  play: 'i-lucide-play',
  terminal: 'i-lucide-terminal',
  shield: 'i-lucide-shield',
  sparkles: 'i-lucide-sparkles',
  zap: 'i-lucide-zap',
  package: 'i-lucide-package',
  pin: 'i-lucide-pin',
  palette: 'i-lucide-palette',
  paintBucket: 'i-lucide-paint-bucket',
  mic: 'i-lucide-mic',
  heading: 'i-lucide-heading',
  briefcase: 'i-lucide-briefcase',
  bookOpen: 'i-lucide-book-open',
  pencil: 'i-lucide-pencil',
  undo: 'i-lucide-undo',
  redo: 'i-lucide-redo'
} as const

export const studioExtraOverrides: Partial<Record<ThemeIcons, Partial<Record<keyof typeof STUDIO_EXTRA_DEFAULTS, string>>>> = {
  // Pixel has no settings/cog (sliders stands in), no pie chart (generic
  // chart) and no up-down chevron (sort). Everything else is a native match.
  pixelarticons: {
    bell: 'i-pixelarticons-bell',
    calendar: 'i-pixelarticons-calendar',
    settings: 'i-pixelarticons-sliders',
    home: 'i-pixelarticons-home',
    inbox: 'i-pixelarticons-inbox',
    logout: 'i-pixelarticons-logout',
    trash: 'i-pixelarticons-trash',
    user: 'i-pixelarticons-user',
    users: 'i-pixelarticons-users',
    userPlus: 'i-pixelarticons-user-plus',
    send: 'i-pixelarticons-send',
    reply: 'i-pixelarticons-reply',
    paperclip: 'i-pixelarticons-paperclip',
    messageCircle: 'i-pixelarticons-message',
    creditCard: 'i-pixelarticons-credit-card',
    dollar: 'i-pixelarticons-dollar',
    cart: 'i-pixelarticons-shopping-cart',
    chart: 'i-pixelarticons-chart',
    list: 'i-pixelarticons-list',
    sort: 'i-pixelarticons-sort',
    mail: 'i-pixelarticons-mail',
    heart: 'i-pixelarticons-heart',
    github: 'i-pixelarticons-github',
    trendingUp: 'i-pixelarticons-trending-up',
    trendingDown: 'i-pixelarticons-trending-down',
    tag: 'i-pixelarticons-label',
    filePlus: 'i-pixelarticons-file-plus',
    folderPlus: 'i-pixelarticons-folder-plus',
    movie: 'i-pixelarticons-movie',
    clock: 'i-pixelarticons-clock',
    coffee: 'i-pixelarticons-coffee',
    globe: 'i-pixelarticons-globe',
    share: 'i-pixelarticons-share',
    link: 'i-pixelarticons-link',
    lock: 'i-pixelarticons-lock',
    filter: 'i-pixelarticons-filter',
    image: 'i-pixelarticons-image',
    camera: 'i-pixelarticons-camera',
    play: 'i-pixelarticons-play',
    terminal: 'i-pixelarticons-terminal',
    shield: 'i-pixelarticons-shield',
    sparkles: 'i-pixelarticons-sparkles',
    zap: 'i-pixelarticons-zap',
    package: 'i-pixelarticons-package',
    pin: 'i-pixelarticons-pin',
    // Pixel has no palette glyph, colors-swatch stands in.
    palette: 'i-pixelarticons-colors-swatch',
    paintBucket: 'i-pixelarticons-paint-bucket',
    mic: 'i-pixelarticons-mic',
    heading: 'i-pixelarticons-heading',
    briefcase: 'i-pixelarticons-briefcase',
    bookOpen: 'i-pixelarticons-book-open',
    pencil: 'i-pixelarticons-pencil',
    undo: 'i-pixelarticons-undo',
    redo: 'i-pixelarticons-redo'
  }
}
