type PhoneCode = {
  name: string
  code: string
  emoji: string
  dialCode: string
  mask: string
}

const phoneCodes: PhoneCode[] = [
  { name: 'Afghanistan', code: 'AF', emoji: '\u{1F1E6}\u{1F1EB}', dialCode: '+93', mask: '## ### ####' },
  { name: 'Albania', code: 'AL', emoji: '\u{1F1E6}\u{1F1F1}', dialCode: '+355', mask: '## ### ####' },
  { name: 'Algeria', code: 'DZ', emoji: '\u{1F1E9}\u{1F1FF}', dialCode: '+213', mask: '### ## ## ##' },
  { name: 'Andorra', code: 'AD', emoji: '\u{1F1E6}\u{1F1E9}', dialCode: '+376', mask: '### ###' },
  { name: 'Angola', code: 'AO', emoji: '\u{1F1E6}\u{1F1F4}', dialCode: '+244', mask: '### ### ###' },
  { name: 'Antigua and Barbuda', code: 'AG', emoji: '\u{1F1E6}\u{1F1EC}', dialCode: '+1-268', mask: '(###) ###-####' },
  { name: 'Argentina', code: 'AR', emoji: '\u{1F1E6}\u{1F1F7}', dialCode: '+54', mask: '## ####-####' },
  { name: 'Armenia', code: 'AM', emoji: '\u{1F1E6}\u{1F1F2}', dialCode: '+374', mask: '## ######' },
  { name: 'Australia', code: 'AU', emoji: '\u{1F1E6}\u{1F1FA}', dialCode: '+61', mask: '### ### ###' },
  { name: 'Austria', code: 'AT', emoji: '\u{1F1E6}\u{1F1F9}', dialCode: '+43', mask: '### #######' },
  { name: 'Azerbaijan', code: 'AZ', emoji: '\u{1F1E6}\u{1F1FF}', dialCode: '+994', mask: '## ### ## ##' },
  { name: 'Bahamas', code: 'BS', emoji: '\u{1F1E7}\u{1F1F8}', dialCode: '+1-242', mask: '(###) ###-####' },
  { name: 'Bahrain', code: 'BH', emoji: '\u{1F1E7}\u{1F1ED}', dialCode: '+973', mask: '#### ####' },
  { name: 'Bangladesh', code: 'BD', emoji: '\u{1F1E7}\u{1F1E9}', dialCode: '+880', mask: '####-######' },
  { name: 'Barbados', code: 'BB', emoji: '\u{1F1E7}\u{1F1E7}', dialCode: '+1-246', mask: '(###) ###-####' },
  { name: 'Belarus', code: 'BY', emoji: '\u{1F1E7}\u{1F1FE}', dialCode: '+375', mask: '## ###-##-##' },
  { name: 'Belgium', code: 'BE', emoji: '\u{1F1E7}\u{1F1EA}', dialCode: '+32', mask: '### ## ## ##' },
  { name: 'Belize', code: 'BZ', emoji: '\u{1F1E7}\u{1F1FF}', dialCode: '+501', mask: '###-####' },
  { name: 'Benin', code: 'BJ', emoji: '\u{1F1E7}\u{1F1EF}', dialCode: '+229', mask: '## ## ## ##' },
  { name: 'Bhutan', code: 'BT', emoji: '\u{1F1E7}\u{1F1F9}', dialCode: '+975', mask: '## ## ## ##' },
  { name: 'Bolivia', code: 'BO', emoji: '\u{1F1E7}\u{1F1F4}', dialCode: '+591', mask: '########' },
  { name: 'Bosnia and Herzegovina', code: 'BA', emoji: '\u{1F1E7}\u{1F1E6}', dialCode: '+387', mask: '## ###-###' },
  { name: 'Botswana', code: 'BW', emoji: '\u{1F1E7}\u{1F1FC}', dialCode: '+267', mask: '## ### ###' },
  { name: 'Brazil', code: 'BR', emoji: '\u{1F1E7}\u{1F1F7}', dialCode: '+55', mask: '(##) #####-####' },
  { name: 'Brunei', code: 'BN', emoji: '\u{1F1E7}\u{1F1F3}', dialCode: '+673', mask: '### ####' },
  { name: 'Bulgaria', code: 'BG', emoji: '\u{1F1E7}\u{1F1EC}', dialCode: '+359', mask: '### ### ###' },
  { name: 'Burkina Faso', code: 'BF', emoji: '\u{1F1E7}\u{1F1EB}', dialCode: '+226', mask: '## ## ## ##' },
  { name: 'Burundi', code: 'BI', emoji: '\u{1F1E7}\u{1F1EE}', dialCode: '+257', mask: '## ## ## ##' },
  { name: 'Cambodia', code: 'KH', emoji: '\u{1F1F0}\u{1F1ED}', dialCode: '+855', mask: '## ### ###' },
  { name: 'Cameroon', code: 'CM', emoji: '\u{1F1E8}\u{1F1F2}', dialCode: '+237', mask: '# ## ## ## ##' },
  { name: 'Canada', code: 'CA', emoji: '\u{1F1E8}\u{1F1E6}', dialCode: '+1', mask: '(###) ###-####' },
  { name: 'Cape Verde', code: 'CV', emoji: '\u{1F1E8}\u{1F1FB}', dialCode: '+238', mask: '### ## ##' },
  { name: 'Central African Republic', code: 'CF', emoji: '\u{1F1E8}\u{1F1EB}', dialCode: '+236', mask: '## ## ## ##' },
  { name: 'Chad', code: 'TD', emoji: '\u{1F1F9}\u{1F1E9}', dialCode: '+235', mask: '## ## ## ##' },
  { name: 'Chile', code: 'CL', emoji: '\u{1F1E8}\u{1F1F1}', dialCode: '+56', mask: '# #### ####' },
  { name: 'China', code: 'CN', emoji: '\u{1F1E8}\u{1F1F3}', dialCode: '+86', mask: '###-####-####' },
  { name: 'Colombia', code: 'CO', emoji: '\u{1F1E8}\u{1F1F4}', dialCode: '+57', mask: '### #######' },
  { name: 'Comoros', code: 'KM', emoji: '\u{1F1F0}\u{1F1F2}', dialCode: '+269', mask: '### ## ##' },
  { name: 'Congo', code: 'CG', emoji: '\u{1F1E8}\u{1F1EC}', dialCode: '+242', mask: '## ### ####' },
  { name: 'Costa Rica', code: 'CR', emoji: '\u{1F1E8}\u{1F1F7}', dialCode: '+506', mask: '#### ####' },
  { name: 'Croatia', code: 'HR', emoji: '\u{1F1ED}\u{1F1F7}', dialCode: '+385', mask: '## ### ####' },
  { name: 'Cuba', code: 'CU', emoji: '\u{1F1E8}\u{1F1FA}', dialCode: '+53', mask: '# ### ####' },
  { name: 'Cyprus', code: 'CY', emoji: '\u{1F1E8}\u{1F1FE}', dialCode: '+357', mask: '## ######' },
  { name: 'Czech Republic', code: 'CZ', emoji: '\u{1F1E8}\u{1F1FF}', dialCode: '+420', mask: '### ### ###' },
  { name: 'Denmark', code: 'DK', emoji: '\u{1F1E9}\u{1F1F0}', dialCode: '+45', mask: '## ## ## ##' },
  { name: 'Djibouti', code: 'DJ', emoji: '\u{1F1E9}\u{1F1EF}', dialCode: '+253', mask: '## ## ## ##' },
  { name: 'Dominica', code: 'DM', emoji: '\u{1F1E9}\u{1F1F2}', dialCode: '+1-767', mask: '(###) ###-####' },
  { name: 'Dominican Republic', code: 'DO', emoji: '\u{1F1E9}\u{1F1F4}', dialCode: '+1-809', mask: '(###) ###-####' },
  { name: 'East Timor', code: 'TL', emoji: '\u{1F1F9}\u{1F1F1}', dialCode: '+670', mask: '#### ####' },
  { name: 'Ecuador', code: 'EC', emoji: '\u{1F1EA}\u{1F1E8}', dialCode: '+593', mask: '## ### ####' },
  { name: 'Egypt', code: 'EG', emoji: '\u{1F1EA}\u{1F1EC}', dialCode: '+20', mask: '### ### ####' },
  { name: 'El Salvador', code: 'SV', emoji: '\u{1F1F8}\u{1F1FB}', dialCode: '+503', mask: '#### ####' },
  { name: 'Equatorial Guinea', code: 'GQ', emoji: '\u{1F1EC}\u{1F1F6}', dialCode: '+240', mask: '### ### ###' },
  { name: 'Eritrea', code: 'ER', emoji: '\u{1F1EA}\u{1F1F7}', dialCode: '+291', mask: '# ### ###' },
  { name: 'Estonia', code: 'EE', emoji: '\u{1F1EA}\u{1F1EA}', dialCode: '+372', mask: '#### ####' },
  { name: 'Ethiopia', code: 'ET', emoji: '\u{1F1EA}\u{1F1F9}', dialCode: '+251', mask: '## ### ####' },
  { name: 'Fiji', code: 'FJ', emoji: '\u{1F1EB}\u{1F1EF}', dialCode: '+679', mask: '### ####' },
  { name: 'Finland', code: 'FI', emoji: '\u{1F1EB}\u{1F1EE}', dialCode: '+358', mask: '## ### ## ##' },
  { name: 'France', code: 'FR', emoji: '\u{1F1EB}\u{1F1F7}', dialCode: '+33', mask: '# ## ## ## ##' },
  { name: 'Gabon', code: 'GA', emoji: '\u{1F1EC}\u{1F1E6}', dialCode: '+241', mask: '# ## ## ##' },
  { name: 'Gambia', code: 'GM', emoji: '\u{1F1EC}\u{1F1F2}', dialCode: '+220', mask: '### ####' },
  { name: 'Georgia', code: 'GE', emoji: '\u{1F1EC}\u{1F1EA}', dialCode: '+995', mask: '### ## ## ##' },
  { name: 'Germany', code: 'DE', emoji: '\u{1F1E9}\u{1F1EA}', dialCode: '+49', mask: '### #######' },
  { name: 'Ghana', code: 'GH', emoji: '\u{1F1EC}\u{1F1ED}', dialCode: '+233', mask: '## ### ####' },
  { name: 'Greece', code: 'GR', emoji: '\u{1F1EC}\u{1F1F7}', dialCode: '+30', mask: '### ### ####' },
  { name: 'Grenada', code: 'GD', emoji: '\u{1F1EC}\u{1F1E9}', dialCode: '+1-473', mask: '(###) ###-####' },
  { name: 'Guatemala', code: 'GT', emoji: '\u{1F1EC}\u{1F1F9}', dialCode: '+502', mask: '#### ####' },
  { name: 'Guinea', code: 'GN', emoji: '\u{1F1EC}\u{1F1F3}', dialCode: '+224', mask: '### ## ## ##' },
  { name: 'Guinea-Bissau', code: 'GW', emoji: '\u{1F1EC}\u{1F1FC}', dialCode: '+245', mask: '### ####' },
  { name: 'Guyana', code: 'GY', emoji: '\u{1F1EC}\u{1F1FE}', dialCode: '+592', mask: '### ####' },
  { name: 'Haiti', code: 'HT', emoji: '\u{1F1ED}\u{1F1F9}', dialCode: '+509', mask: '## ## ####' },
  { name: 'Honduras', code: 'HN', emoji: '\u{1F1ED}\u{1F1F3}', dialCode: '+504', mask: '####-####' },
  { name: 'Hungary', code: 'HU', emoji: '\u{1F1ED}\u{1F1FA}', dialCode: '+36', mask: '## ### ####' },
  { name: 'Iceland', code: 'IS', emoji: '\u{1F1EE}\u{1F1F8}', dialCode: '+354', mask: '### ####' },
  { name: 'India', code: 'IN', emoji: '\u{1F1EE}\u{1F1F3}', dialCode: '+91', mask: '#####-#####' },
  { name: 'Indonesia', code: 'ID', emoji: '\u{1F1EE}\u{1F1E9}', dialCode: '+62', mask: '###-###-####' },
  { name: 'Iran', code: 'IR', emoji: '\u{1F1EE}\u{1F1F7}', dialCode: '+98', mask: '### ### ####' },
  { name: 'Iraq', code: 'IQ', emoji: '\u{1F1EE}\u{1F1F6}', dialCode: '+964', mask: '### ### ####' },
  { name: 'Ireland', code: 'IE', emoji: '\u{1F1EE}\u{1F1EA}', dialCode: '+353', mask: '## ### ####' },
  { name: 'Israel', code: 'IL', emoji: '\u{1F1EE}\u{1F1F1}', dialCode: '+972', mask: '##-###-####' },
  { name: 'Italy', code: 'IT', emoji: '\u{1F1EE}\u{1F1F9}', dialCode: '+39', mask: '### ### ####' },
  { name: 'Jamaica', code: 'JM', emoji: '\u{1F1EF}\u{1F1F2}', dialCode: '+1-876', mask: '(###) ###-####' },
  { name: 'Japan', code: 'JP', emoji: '\u{1F1EF}\u{1F1F5}', dialCode: '+81', mask: '##-####-####' },
  { name: 'Jordan', code: 'JO', emoji: '\u{1F1EF}\u{1F1F4}', dialCode: '+962', mask: '# #### ####' },
  { name: 'Kazakhstan', code: 'KZ', emoji: '\u{1F1F0}\u{1F1FF}', dialCode: '+7', mask: '### ### ## ##' },
  { name: 'Kenya', code: 'KE', emoji: '\u{1F1F0}\u{1F1EA}', dialCode: '+254', mask: '### ######' },
  { name: 'Kiribati', code: 'KI', emoji: '\u{1F1F0}\u{1F1EE}', dialCode: '+686', mask: '########' },
  { name: 'Kuwait', code: 'KW', emoji: '\u{1F1F0}\u{1F1FC}', dialCode: '+965', mask: '#### ####' },
  { name: 'Kyrgyzstan', code: 'KG', emoji: '\u{1F1F0}\u{1F1EC}', dialCode: '+996', mask: '### ### ###' },
  { name: 'Laos', code: 'LA', emoji: '\u{1F1F1}\u{1F1E6}', dialCode: '+856', mask: '## ## ### ###' },
  { name: 'Latvia', code: 'LV', emoji: '\u{1F1F1}\u{1F1FB}', dialCode: '+371', mask: '## ### ###' },
  { name: 'Lebanon', code: 'LB', emoji: '\u{1F1F1}\u{1F1E7}', dialCode: '+961', mask: '## ### ###' },
  { name: 'Lesotho', code: 'LS', emoji: '\u{1F1F1}\u{1F1F8}', dialCode: '+266', mask: '#### ####' },
  { name: 'Liberia', code: 'LR', emoji: '\u{1F1F1}\u{1F1F7}', dialCode: '+231', mask: '### ### ####' },
  { name: 'Libya', code: 'LY', emoji: '\u{1F1F1}\u{1F1FE}', dialCode: '+218', mask: '##-#######' },
  { name: 'Liechtenstein', code: 'LI', emoji: '\u{1F1F1}\u{1F1EE}', dialCode: '+423', mask: '### ####' },
  { name: 'Lithuania', code: 'LT', emoji: '\u{1F1F1}\u{1F1F9}', dialCode: '+370', mask: '### #####' },
  { name: 'Luxembourg', code: 'LU', emoji: '\u{1F1F1}\u{1F1FA}', dialCode: '+352', mask: '### ### ###' },
  { name: 'Madagascar', code: 'MG', emoji: '\u{1F1F2}\u{1F1EC}', dialCode: '+261', mask: '## ## ### ##' },
  { name: 'Malawi', code: 'MW', emoji: '\u{1F1F2}\u{1F1FC}', dialCode: '+265', mask: '## ### ####' },
  { name: 'Malaysia', code: 'MY', emoji: '\u{1F1F2}\u{1F1FE}', dialCode: '+60', mask: '##-### ####' },
  { name: 'Maldives', code: 'MV', emoji: '\u{1F1F2}\u{1F1FB}', dialCode: '+960', mask: '###-####' },
  { name: 'Mali', code: 'ML', emoji: '\u{1F1F2}\u{1F1F1}', dialCode: '+223', mask: '## ## ## ##' },
  { name: 'Malta', code: 'MT', emoji: '\u{1F1F2}\u{1F1F9}', dialCode: '+356', mask: '#### ####' },
  { name: 'Marshall Islands', code: 'MH', emoji: '\u{1F1F2}\u{1F1ED}', dialCode: '+692', mask: '###-####' },
  { name: 'Mauritania', code: 'MR', emoji: '\u{1F1F2}\u{1F1F7}', dialCode: '+222', mask: '## ## ## ##' },
  { name: 'Mauritius', code: 'MU', emoji: '\u{1F1F2}\u{1F1FA}', dialCode: '+230', mask: '#### ####' },
  { name: 'Mexico', code: 'MX', emoji: '\u{1F1F2}\u{1F1FD}', dialCode: '+52', mask: '(##) ####-####' },
  { name: 'Micronesia', code: 'FM', emoji: '\u{1F1EB}\u{1F1F2}', dialCode: '+691', mask: '### ####' },
  { name: 'Moldova', code: 'MD', emoji: '\u{1F1F2}\u{1F1E9}', dialCode: '+373', mask: '### ## ###' },
  { name: 'Monaco', code: 'MC', emoji: '\u{1F1F2}\u{1F1E8}', dialCode: '+377', mask: '## ## ## ##' },
  { name: 'Mongolia', code: 'MN', emoji: '\u{1F1F2}\u{1F1F3}', dialCode: '+976', mask: '#### ####' },
  { name: 'Montenegro', code: 'ME', emoji: '\u{1F1F2}\u{1F1EA}', dialCode: '+382', mask: '## ### ###' },
  { name: 'Morocco', code: 'MA', emoji: '\u{1F1F2}\u{1F1E6}', dialCode: '+212', mask: '##-######' },
  { name: 'Mozambique', code: 'MZ', emoji: '\u{1F1F2}\u{1F1FF}', dialCode: '+258', mask: '## ### ####' },
  { name: 'Myanmar', code: 'MM', emoji: '\u{1F1F2}\u{1F1F2}', dialCode: '+95', mask: '# ### ####' },
  { name: 'Namibia', code: 'NA', emoji: '\u{1F1F3}\u{1F1E6}', dialCode: '+264', mask: '## ### ####' },
  { name: 'Nauru', code: 'NR', emoji: '\u{1F1F3}\u{1F1F7}', dialCode: '+674', mask: '### ####' },
  { name: 'Nepal', code: 'NP', emoji: '\u{1F1F3}\u{1F1F5}', dialCode: '+977', mask: '###-#######' },
  { name: 'Netherlands', code: 'NL', emoji: '\u{1F1F3}\u{1F1F1}', dialCode: '+31', mask: '# ########' },
  { name: 'New Zealand', code: 'NZ', emoji: '\u{1F1F3}\u{1F1FF}', dialCode: '+64', mask: '## ### ####' },
  { name: 'Nicaragua', code: 'NI', emoji: '\u{1F1F3}\u{1F1EE}', dialCode: '+505', mask: '#### ####' },
  { name: 'Niger', code: 'NE', emoji: '\u{1F1F3}\u{1F1EA}', dialCode: '+227', mask: '## ## ## ##' },
  { name: 'Nigeria', code: 'NG', emoji: '\u{1F1F3}\u{1F1EC}', dialCode: '+234', mask: '### ### ####' },
  { name: 'North Macedonia', code: 'MK', emoji: '\u{1F1F2}\u{1F1F0}', dialCode: '+389', mask: '## ### ###' },
  { name: 'Norway', code: 'NO', emoji: '\u{1F1F3}\u{1F1F4}', dialCode: '+47', mask: '### ## ###' },
  { name: 'Oman', code: 'OM', emoji: '\u{1F1F4}\u{1F1F2}', dialCode: '+968', mask: '#### ####' },
  { name: 'Pakistan', code: 'PK', emoji: '\u{1F1F5}\u{1F1F0}', dialCode: '+92', mask: '### #######' },
  { name: 'Palau', code: 'PW', emoji: '\u{1F1F5}\u{1F1FC}', dialCode: '+680', mask: '### ####' },
  { name: 'Palestine', code: 'PS', emoji: '\u{1F1F5}\u{1F1F8}', dialCode: '+970', mask: '### ## ####' },
  { name: 'Panama', code: 'PA', emoji: '\u{1F1F5}\u{1F1E6}', dialCode: '+507', mask: '####-####' },
  { name: 'Papua New Guinea', code: 'PG', emoji: '\u{1F1F5}\u{1F1EC}', dialCode: '+675', mask: '### ####' },
  { name: 'Paraguay', code: 'PY', emoji: '\u{1F1F5}\u{1F1FE}', dialCode: '+595', mask: '### ######' },
  { name: 'Peru', code: 'PE', emoji: '\u{1F1F5}\u{1F1EA}', dialCode: '+51', mask: '### ### ###' },
  { name: 'Philippines', code: 'PH', emoji: '\u{1F1F5}\u{1F1ED}', dialCode: '+63', mask: '### ### ####' },
  { name: 'Poland', code: 'PL', emoji: '\u{1F1F5}\u{1F1F1}', dialCode: '+48', mask: '### ### ###' },
  { name: 'Portugal', code: 'PT', emoji: '\u{1F1F5}\u{1F1F9}', dialCode: '+351', mask: '### ### ###' },
  { name: 'Qatar', code: 'QA', emoji: '\u{1F1F6}\u{1F1E6}', dialCode: '+974', mask: '#### ####' },
  { name: 'Romania', code: 'RO', emoji: '\u{1F1F7}\u{1F1F4}', dialCode: '+40', mask: '### ### ###' },
  { name: 'Russia', code: 'RU', emoji: '\u{1F1F7}\u{1F1FA}', dialCode: '+7', mask: '### ###-##-##' },
  { name: 'Rwanda', code: 'RW', emoji: '\u{1F1F7}\u{1F1FC}', dialCode: '+250', mask: '### ### ###' },
  { name: 'Saint Kitts and Nevis', code: 'KN', emoji: '\u{1F1F0}\u{1F1F3}', dialCode: '+1-869', mask: '(###) ###-####' },
  { name: 'Saint Lucia', code: 'LC', emoji: '\u{1F1F1}\u{1F1E8}', dialCode: '+1-758', mask: '(###) ###-####' },
  { name: 'Saint Vincent and the Grenadines', code: 'VC', emoji: '\u{1F1FB}\u{1F1E8}', dialCode: '+1-784', mask: '(###) ###-####' },
  { name: 'Samoa', code: 'WS', emoji: '\u{1F1FC}\u{1F1F8}', dialCode: '+685', mask: '## ####' },
  { name: 'San Marino', code: 'SM', emoji: '\u{1F1F8}\u{1F1F2}', dialCode: '+378', mask: '#### ######' },
  { name: 'Sao Tome and Principe', code: 'ST', emoji: '\u{1F1F8}\u{1F1F9}', dialCode: '+239', mask: '### ####' },
  { name: 'Saudi Arabia', code: 'SA', emoji: '\u{1F1F8}\u{1F1E6}', dialCode: '+966', mask: '## ### ####' },
  { name: 'Senegal', code: 'SN', emoji: '\u{1F1F8}\u{1F1F3}', dialCode: '+221', mask: '## ### ## ##' },
  { name: 'Serbia', code: 'RS', emoji: '\u{1F1F7}\u{1F1F8}', dialCode: '+381', mask: '## #######' },
  { name: 'Seychelles', code: 'SC', emoji: '\u{1F1F8}\u{1F1E8}', dialCode: '+248', mask: '# ### ###' },
  { name: 'Sierra Leone', code: 'SL', emoji: '\u{1F1F8}\u{1F1F1}', dialCode: '+232', mask: '## ######' },
  { name: 'Singapore', code: 'SG', emoji: '\u{1F1F8}\u{1F1EC}', dialCode: '+65', mask: '#### ####' },
  { name: 'Slovakia', code: 'SK', emoji: '\u{1F1F8}\u{1F1F0}', dialCode: '+421', mask: '### ### ###' },
  { name: 'Slovenia', code: 'SI', emoji: '\u{1F1F8}\u{1F1EE}', dialCode: '+386', mask: '## ### ###' },
  { name: 'Solomon Islands', code: 'SB', emoji: '\u{1F1F8}\u{1F1E7}', dialCode: '+677', mask: '## #####' },
  { name: 'Somalia', code: 'SO', emoji: '\u{1F1F8}\u{1F1F4}', dialCode: '+252', mask: '## #######' },
  { name: 'South Africa', code: 'ZA', emoji: '\u{1F1FF}\u{1F1E6}', dialCode: '+27', mask: '## ### ####' },
  { name: 'South Korea', code: 'KR', emoji: '\u{1F1F0}\u{1F1F7}', dialCode: '+82', mask: '##-####-####' },
  { name: 'South Sudan', code: 'SS', emoji: '\u{1F1F8}\u{1F1F8}', dialCode: '+211', mask: '## ### ####' },
  { name: 'Spain', code: 'ES', emoji: '\u{1F1EA}\u{1F1F8}', dialCode: '+34', mask: '### ## ## ##' },
  { name: 'Sri Lanka', code: 'LK', emoji: '\u{1F1F1}\u{1F1F0}', dialCode: '+94', mask: '## ### ####' },
  { name: 'Sudan', code: 'SD', emoji: '\u{1F1F8}\u{1F1E9}', dialCode: '+249', mask: '## ### ####' },
  { name: 'Suriname', code: 'SR', emoji: '\u{1F1F8}\u{1F1F7}', dialCode: '+597', mask: '###-####' },
  { name: 'Sweden', code: 'SE', emoji: '\u{1F1F8}\u{1F1EA}', dialCode: '+46', mask: '##-### ## ##' },
  { name: 'Switzerland', code: 'CH', emoji: '\u{1F1E8}\u{1F1ED}', dialCode: '+41', mask: '## ### ## ##' },
  { name: 'Syria', code: 'SY', emoji: '\u{1F1F8}\u{1F1FE}', dialCode: '+963', mask: '### ### ####' },
  { name: 'Taiwan', code: 'TW', emoji: '\u{1F1F9}\u{1F1FC}', dialCode: '+886', mask: '### ### ###' },
  { name: 'Tajikistan', code: 'TJ', emoji: '\u{1F1F9}\u{1F1EF}', dialCode: '+992', mask: '## ### ####' },
  { name: 'Tanzania', code: 'TZ', emoji: '\u{1F1F9}\u{1F1FF}', dialCode: '+255', mask: '### ### ###' },
  { name: 'Thailand', code: 'TH', emoji: '\u{1F1F9}\u{1F1ED}', dialCode: '+66', mask: '## ### ####' },
  { name: 'Togo', code: 'TG', emoji: '\u{1F1F9}\u{1F1EC}', dialCode: '+228', mask: '## ## ## ##' },
  { name: 'Tonga', code: 'TO', emoji: '\u{1F1F9}\u{1F1F4}', dialCode: '+676', mask: '### ####' },
  { name: 'Trinidad and Tobago', code: 'TT', emoji: '\u{1F1F9}\u{1F1F9}', dialCode: '+1-868', mask: '(###) ###-####' },
  { name: 'Tunisia', code: 'TN', emoji: '\u{1F1F9}\u{1F1F3}', dialCode: '+216', mask: '## ### ###' },
  { name: 'Turkey', code: 'TR', emoji: '\u{1F1F9}\u{1F1F7}', dialCode: '+90', mask: '### ### ## ##' },
  { name: 'Turkmenistan', code: 'TM', emoji: '\u{1F1F9}\u{1F1F2}', dialCode: '+993', mask: '## ######' },
  { name: 'Tuvalu', code: 'TV', emoji: '\u{1F1F9}\u{1F1FB}', dialCode: '+688', mask: '######' },
  { name: 'Uganda', code: 'UG', emoji: '\u{1F1FA}\u{1F1EC}', dialCode: '+256', mask: '### ######' },
  { name: 'Ukraine', code: 'UA', emoji: '\u{1F1FA}\u{1F1E6}', dialCode: '+380', mask: '## ### ## ##' },
  { name: 'United Arab Emirates', code: 'AE', emoji: '\u{1F1E6}\u{1F1EA}', dialCode: '+971', mask: '## ### ####' },
  { name: 'United Kingdom', code: 'GB', emoji: '\u{1F1EC}\u{1F1E7}', dialCode: '+44', mask: '#### ######' },
  { name: 'United States', code: 'US', emoji: '\u{1F1FA}\u{1F1F8}', dialCode: '+1', mask: '(###) ###-####' },
  { name: 'Uruguay', code: 'UY', emoji: '\u{1F1FA}\u{1F1FE}', dialCode: '+598', mask: '## ### ###' },
  { name: 'Uzbekistan', code: 'UZ', emoji: '\u{1F1FA}\u{1F1FF}', dialCode: '+998', mask: '## ### ## ##' },
  { name: 'Vanuatu', code: 'VU', emoji: '\u{1F1FB}\u{1F1FA}', dialCode: '+678', mask: '### ####' },
  { name: 'Vatican City', code: 'VA', emoji: '\u{1F1FB}\u{1F1E6}', dialCode: '+379', mask: '## #### ####' },
  { name: 'Venezuela', code: 'VE', emoji: '\u{1F1FB}\u{1F1EA}', dialCode: '+58', mask: '###-#######' },
  { name: 'Vietnam', code: 'VN', emoji: '\u{1F1FB}\u{1F1F3}', dialCode: '+84', mask: '## ### ## ##' },
  { name: 'Yemen', code: 'YE', emoji: '\u{1F1FE}\u{1F1EA}', dialCode: '+967', mask: '### ### ###' },
  { name: 'Zambia', code: 'ZM', emoji: '\u{1F1FF}\u{1F1F2}', dialCode: '+260', mask: '## #######' },
  { name: 'Zimbabwe', code: 'ZW', emoji: '\u{1F1FF}\u{1F1FC}', dialCode: '+263', mask: '## ### ####' }
]

export default eventHandler(async () => phoneCodes)
