export const pg = {
  absolute_inset_0_size_full_stroke_inverted_10: 'absolute inset-0 size-full stroke-inverted/10',
  absolute_top_0_inset_x_0_lg_border_b_0: 'absolute top-0 inset-x-0 lg:border-b-0',
  absolute_top_0_inset_x_0_z_5_bg_default: 'absolute top-0 inset-x-0 z-5 bg-default',
  absolute_top_0_inset_x_0_z_5_border_b_0_lg_pointer_events_none: 'absolute top-0 inset-x-0 z-5 border-b-0 lg:pointer-events-none',
  animate_spin: 'animate-spin',
  basis_1_3: 'basis-1/3',
  basis_70_transition_opacity_ease_in_out_not_is_snapped_opacity_10: 'basis-[70%] transition-opacity ease-in-out [&:not(.is-snapped)]:opacity-10',
  bg_elevated_25: 'bg-elevated/25',
  bg_elevated_50_border_border_default_rounded_xl_items_center_justify_center_text_muted_fon: 'bg-elevated/50 border border-default rounded-xl items-center justify-center text-muted font-semibold',
  bg_neutral_50_dark_bg_neutral_950: 'bg-neutral-50 dark:bg-neutral-950',
  border_b_0: 'border-b-0',
  border_border_accented_rounded_sm: 'border border-accented rounded-sm',
  border_border_default_rounded_lg: 'border border-default rounded-lg',
  border_t_border_default_mt_4: 'border-t border-default mt-4',
  border_t_border_default_p_4: 'border-t border-default p-4',
  capitalize: 'capitalize',
  chip: 'rounded-full ring ring-bg bg-(--chip-light) dark:bg-(--chip-dark) size-2',
  data_orientation_horizontal_border_b_border_default: 'data-[orientation=horizontal]:border-b border-default',
  data_orientation_horizontal_w_full: 'data-[orientation=horizontal]:w-full',
  data_orientation_horizontal_w_full_data_orientation_vertical_w_96_min_h_0: 'data-[orientation=horizontal]:w-full data-[orientation=vertical]:w-96 min-h-0',
  data_orientation_horizontal_w_lg: 'data-[orientation=horizontal]:w-lg',
  data_orientation_vertical_data_collapsed_false_w_48: 'data-[orientation=vertical]:data-[collapsed=false]:w-48',
  data_orientation_vertical_w_80: 'data-[orientation=vertical]:w-80',
  data_orientation_vertical_w_96: 'data-[orientation=vertical]:w-96',
  data_state_open_bg_elevated: 'data-[state=open]:bg-elevated',
  first_mt_0_last_mb_0: '*:first:mt-0 *:last:mb-0',
  flex_1: 'flex-1',
  flex_1_flex_flex_col_gap_4_sm_gap_6_max_w_xl_w_full_mx_auto_min_h_0: 'flex-1 flex flex-col gap-4 sm:gap-6 max-w-xl w-full mx-auto min-h-0',
  flex_1_flex_flex_col_overflow_hidden_lg_peer_data_variant_floating_my_4_peer_data_variant_: 'flex-1 flex flex-col overflow-hidden lg:peer-data-[variant=floating]:my-4 peer-data-[variant=inset]:m-4 lg:peer-data-[variant=inset]:mx-0 peer-data-[variant=inset]:rounded-xl peer-data-[variant=inset]:shadow-sm peer-data-[variant=inset]:ring peer-data-[variant=inset]:ring-default bg-default',
  flex_1_m_4: 'flex-1 m-4',
  flex_1_p_4_sm_px_6: 'flex-1 p-4 sm:px-6',
  flex_1_text_center: 'flex-1 text-center',
  flex_1_w_full: 'flex-1 w-full',
  flex_col: 'flex-col',
  flex_col_gap_4: 'flex-col gap-4',
  flex_col_w_full: 'flex-col w-full',
  flex_flex_1: 'flex flex-1',
  flex_flex_col_flex_1_gap_4_w_full_max_h_calc_100vh_7rem: 'flex flex-col flex-1 gap-4 w-full max-h-[calc(100vh-7rem)]',
  flex_flex_col_gap_10_min_h_0: 'flex flex-col gap-10 min-h-0',
  flex_flex_col_gap_2: 'flex flex-col gap-2',
  flex_flex_col_gap_2_min_h_0: 'flex flex-col gap-2 min-h-0',
  flex_flex_col_gap_2_w_48: 'flex flex-col gap-2 w-48',
  flex_flex_col_gap_3: 'flex flex-col gap-3',
  flex_flex_col_gap_4: 'flex flex-col gap-4',
  flex_flex_col_gap_4_min_h_0: 'flex flex-col gap-4 min-h-0',
  flex_flex_col_gap_8: 'flex flex-col gap-8',
  flex_flex_col_gap_8_min_h_0_mt_16_pb_8: 'flex flex-col gap-8 min-h-0 mt-16 pb-8',
  flex_flex_col_items_center_gap_4: 'flex flex-col items-center gap-4',
  flex_flex_col_items_center_justify_center_min_h_full_shrink_0: 'flex flex-col items-center justify-center min-h-full shrink-0',
  flex_flex_col_items_start_gap_2: 'flex flex-col items-start gap-2',
  flex_flex_col_items_start_gap_2_text_sm: 'flex flex-col items-start gap-2 text-sm',
  flex_flex_wrap_gap_2: 'flex flex-wrap gap-2',
  flex_flex_wrap_items_center_gap_3: 'flex flex-wrap items-center gap-3',
  flex_gap_2: 'flex gap-2',
  flex_gap_2_justify_between: 'flex gap-2 justify-between',
  flex_gap_2_mt_8: 'flex gap-2 mt-8',
  flex_gap_4: 'flex gap-4',
  flex_items_center_gap_1: 'flex items-center gap-1',
  flex_items_center_gap_1_5: 'flex items-center gap-1.5',
  flex_items_center_gap_2: 'flex items-center gap-2',
  flex_items_center_gap_2_my_2: 'flex items-center gap-2 my-2',
  flex_items_center_gap_2_px_2_py_1_text_sm_text_muted_hover_text_default_hover_bg_elevated_: 'flex items-center gap-2 px-2 py-1 text-sm text-muted hover:text-default hover:bg-elevated/50 transition-colors min-w-0 rounded-md',
  flex_items_center_gap_4: 'flex items-center gap-4',
  flex_items_center_gap_6: 'flex items-center gap-6',
  flex_items_center_justify_between: 'flex items-center justify-between',
  flex_items_center_justify_between_gap_2: 'flex items-center justify-between gap-2',
  flex_items_center_justify_between_gap_3: 'flex items-center justify-between gap-3',
  flex_items_center_justify_between_gap_4: 'flex items-center justify-between gap-4',
  flex_items_center_justify_center_rounded_md_border_border_dashed_border_accented_text_sm_a: 'flex items-center justify-center rounded-md border border-dashed border-accented text-sm aspect-video w-72',
  flex_items_center_me_0_5: 'flex items-center me-0.5',
  flex_items_center_ms_auto: 'flex items-center ms-auto',
  flex_items_start_gap_2_min_h_0: 'flex items-start gap-2 min-h-0',
  flex_justify_center_gap_2_p_4_w_48: 'flex justify-center gap-2 p-4 w-48',
  flex_justify_end: 'flex justify-end',
  font_bold: 'font-bold',
  font_bold_rounded_full: 'font-bold rounded-full',
  font_medium: 'font-medium',
  font_mono_text_sm: 'font-mono text-sm',
  font_semibold_text_green_700: 'font-semibold text-green-700',
  font_semibold_text_highlighted: 'font-semibold text-highlighted',
  gap_4: 'gap-4',
  gap_4_data_orientation_horizontal_w_48_data_orientation_vertical_h_48_data_orientation_ver: 'gap-4 data-[orientation=horizontal]:w-48 data-[orientation=vertical]:h-48 data-[orientation=vertical]:flex-row',
  gap_4_data_orientation_horizontal_w_64_data_orientation_vertical_h_64_data_orientation_ver: 'gap-4 data-[orientation=horizontal]:w-64 data-[orientation=vertical]:h-64 data-[orientation=vertical]:flex-row',
  gap_4_flex_flex_col_w_60: 'gap-4 flex flex-col w-60',
  gap_5: 'gap-5',
  gap_8: 'gap-8',
  gap_8_data_orientation_horizontal_w_48_data_orientation_vertical_h_48_data_orientation_ver: 'gap-8 data-[orientation=horizontal]:w-48 data-[orientation=vertical]:h-48 data-[orientation=vertical]:flex-row',
  grid: 'grid',
  grid_grid_cols_2_gap_2: 'grid grid-cols-2 gap-2',
  grid_sm_grid_cols_2_md_grid_cols_3_gap_4: 'grid sm:grid-cols-2 md:grid-cols-3 gap-4',
  group: 'group',
  group_data_state_open_rotate_180_transition_transform_duration_200: 'group-data-[state=open]:rotate-180 transition-transform duration-200',
  h_200px_overflow_y_auto: 'h-[200px] overflow-y-auto',
  h_24: 'h-24',
  h_24_flex_gap_4_items_center: 'h-24 flex gap-4 items-center',
  h_300vh_w_full: 'h-[300vh] w-full',
  h_32: 'h-32',
  h_336px: 'h-[336px]',
  h_352px: 'h-[352px]',
  h_4: 'h-4',
  h_4_w_200px: 'h-4 w-[200px]',
  h_4_w_250px: 'h-4 w-[250px]',
  important_p_0: '!p-0',
  h_48_w_full: 'h-48 w-full',
  h_5_w_auto: 'h-5 w-auto',
  h_6_mx_1: 'h-6 mx-1',
  h_6_w_auto: 'h-6 w-auto',
  h_96_w_full: 'h-96 w-full',
  h_full: 'h-full',
  h_screen_w_full: 'h-screen w-full',
  hidden_md_block: 'hidden md:block',
  hover_text_primary: 'hover:text-primary',
  inline_flex_items_center_justify_center_shrink_0_size_5: 'inline-flex items-center justify-center shrink-0 size-5',
  inline_flex_size_5_rounded_sm: 'inline-flex size-5 rounded-sm',
  italic: 'italic',
  italic_font_bold: 'italic font-bold',
  justify_center: 'justify-center',
  lg_col_span_2_order_first_lg_order_last_top_0_max_h_calc_100vh_12rem: 'lg:col-span-2 order-first lg:order-last top-0 max-h-[calc(100vh-12rem)]',
  lg_col_span_8_max_w_xl_mx_auto_text_muted: 'lg:col-span-8 max-w-xl mx-auto text-muted',
  lowercase: 'lowercase',
  max_w_2xl_mx_auto: 'max-w-2xl mx-auto',
  max_w_80: 'max-w-80',
  max_w_lg: 'max-w-lg',
  max_w_sm: 'max-w-sm',
  max_w_sm_mx_auto_text_muted: 'max-w-sm mx-auto text-muted',
  mb_2_flex_items_center_justify_between: 'mb-2 flex items-center justify-between',
  min_h_0: 'min-h-0',
  min_h_48: 'min-h-48',
  ms_auto: 'ms-auto',
  mt_16: 'mt-16',
  mt_2_5: 'mt-2.5',
  mt_24: 'mt-24',
  mt_8_relative: 'mt-8 relative',
  mx_2_5: '-mx-2.5',
  my_1: '-my-1',
  my_2: '-my-2',
  p_0: 'p-0',
  p_0_5: 'p-0.5',
  p_0_i: 'p-0!',
  p_1_5_overflow_hidden: 'p-1.5 overflow-hidden',
  p_1_border_border_default_rounded_md_max_h_40_overflow_y_auto: 'p-1 border border-default rounded-md max-h-40 overflow-y-auto',
  p_4: 'p-4',
  p_8_max_w_2xl_mx_auto: 'p-8 max-w-2xl mx-auto',
  pointer_events_auto: 'pointer-events-auto',
  px_0: 'px-0',
  px_3_5: 'px-3.5',
  py_2: 'py-2',
  py_2_px_4_flex_gap_4_items_center: 'py-2 px-4 flex gap-4 items-center',
  relative: 'relative',
  relative_overflow_hidden_rounded_sm_border_border_dashed_border_accented_opacity_75_px_4_f: 'relative overflow-hidden rounded-sm border border-dashed border-accented opacity-75 px-4 flex items-center justify-center',
  relative_w_full: 'relative w-full',
  relative_w_full_h_96_overflow_auto: 'relative w-full h-96 overflow-auto',
  ring_0: 'ring-0',
  ring_default: 'ring-default',
  rounded_lg: 'rounded-lg',
  rounded_md_size_full_object_cover: 'rounded-md size-full object-cover',
  self_start: 'self-start',
  shrink_0: 'shrink-0',
  shrink_0_size_5_text_primary: 'shrink-0 size-5 text-primary',
  shrink_overflow_x_auto_py_2: 'shrink overflow-x-auto py-2',
  size_10_shrink_0: 'size-10 shrink-0',
  size_12_rounded_full: 'size-12 rounded-full',
  size_4_shrink_0_rounded_sm: 'size-4 shrink-0 rounded-sm',
  size_4_text_amber_500: 'size-4 text-amber-500',
  size_4_text_green_500: 'size-4 text-green-500',
  size_4_text_muted: 'size-4 text-muted',
  size_48_m_4_inline_flex: 'size-48 m-4 inline-flex',
  size_5_text_dimmed_ml_1: 'size-5 text-dimmed ml-1',
  size_8: 'size-8',
  size_full: 'size-full',
  size_full_animate_pulse: 'size-full animate-pulse',
  size_full_aspect_video: 'size-full aspect-video',
  size_full_flex_flex_col_justify_stretch_items_stretch_gap_4: 'size-full flex flex-col justify-stretch items-stretch gap-4',
  size_full_min_h_48: 'size-full min-h-48',
  size_full_min_h_60_min_w_60: 'size-full min-h-60 min-w-60',
  size_full_min_h_96: 'size-full min-h-96',
  size_full_p_4: 'size-full p-4',
  sm_max_h_96: 'sm:max-h-96',
  sm_px_14: 'sm:px-14',
  space_y_11_min_h_0: 'space-y-11 min-h-0',
  space_y_2: 'space-y-2',
  space_y_4: 'space-y-4',
  sticky_bottom_0: 'sticky bottom-0',
  text_2xl_font_bold_text_primary: 'text-2xl font-bold text-primary',
  text_center_font_semibold: 'text-center font-semibold',
  text_center_min_h_0: 'text-center min-h-0',
  text_center_space_y_4: 'text-center space-y-4',
  text_highlighted: 'text-highlighted',
  text_highlighted_inline_flex: 'text-highlighted inline-flex',
  text_muted: 'text-muted',
  text_muted_text_sm: 'text-muted text-sm',
  text_right: 'text-right',
  text_right_font_medium: 'text-right font-medium',
  text_right_text_green_500_w_48: 'text-right text-green-500 w-48',
  text_sm_font_medium_text_muted: 'text-sm font-medium text-muted',
  text_sm_text_muted: 'text-sm text-muted',
  text_xs: 'text-xs',
  text_xs_text_dimmed_ms_auto_shrink_0: 'text-xs text-dimmed ms-auto shrink-0',
  text_xs_text_muted_mt_1_5: 'text-xs text-muted mt-1.5',
  text_xs_whitespace_pre_wrap: 'text-xs whitespace-pre-wrap',
  top_3_5_rounded_full: 'top-3.5 rounded-full',
  transition_height_duration_200: 'transition-[height] duration-200',
  truncate: 'truncate',
  underline: 'underline',
  w_20: 'w-20',
  w_28: 'w-28',
  w_320px_mx_auto: 'w-[320px] mx-auto',
  w_48: 'w-48',
  w_48_h_16: 'w-48 h-16',
  w_4xl: 'w-4xl',
  w_56: 'w-56',
  w_60: 'w-60',
  w_60_flex_flex_col_gap_4_items_start: 'w-60 flex flex-col gap-4 items-start',
  w_72_flex_flex_col_gap_4_items_start: 'w-72 flex flex-col gap-4 items-start',
  w_80: 'w-80',
  w_96: 'w-96',
  w_96_h_full: 'w-96 h-full',
  w_full: 'w-full',
  w_full_border_t_border_default_divide_y_divide_default_min_h_0: 'w-full border-t border-default divide-y divide-default min-h-0',
  w_full_flex_flex_col_lg_grid_lg_grid_cols_10_lg_gap_10: 'w-full flex flex-col lg:grid lg:grid-cols-10 lg:gap-10',
  w_full_h_80: 'w-full h-80',
  w_full_lg_w_64: 'w-full lg:w-64',
  w_full_max_w_md_mx_auto: 'w-full max-w-md mx-auto',
  w_full_max_w_xl_mx_auto: 'w-full max-w-xl mx-auto',
  w_full_max_w_xs_mx_auto: 'w-full max-w-xs mx-auto',
  w_full_min_h_44: 'w-full min-h-44',
  w_lg: 'w-lg',
  w_xl: 'w-xl',
  whitespace_pre_wrap: 'whitespace-pre-wrap'
} as const
