/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const EffectScope: typeof import('vue')['EffectScope']
  const avatarGroupInjectionKey: typeof import('../src/runtime/composables/useAvatarGroup')['avatarGroupInjectionKey']
  const buttonGroupInjectionKey: typeof import('../src/runtime/composables/useButtonGroup')['buttonGroupInjectionKey']
  const computed: typeof import('vue')['computed']
  const createApp: typeof import('vue')['createApp']
  const customRef: typeof import('vue')['customRef']
  const defineAsyncComponent: typeof import('vue')['defineAsyncComponent']
  const defineComponent: typeof import('vue')['defineComponent']
  const defineLocale: typeof import('../src/runtime/composables/defineLocale')['defineLocale']
  const defineShortcuts: typeof import('../src/runtime/composables/defineShortcuts')['defineShortcuts']
  const effectScope: typeof import('vue')['effectScope']
  const extractShortcuts: typeof import('../src/runtime/composables/defineShortcuts')['extractShortcuts']
  const formBusInjectionKey: typeof import('../src/runtime/composables/useFormField')['formBusInjectionKey']
  const formFieldInjectionKey: typeof import('../src/runtime/composables/useFormField')['formFieldInjectionKey']
  const formInputsInjectionKey: typeof import('../src/runtime/composables/useFormField')['formInputsInjectionKey']
  const formLoadingInjectionKey: typeof import('../src/runtime/composables/useFormField')['formLoadingInjectionKey']
  const formOptionsInjectionKey: typeof import('../src/runtime/composables/useFormField')['formOptionsInjectionKey']
  const getCurrentInstance: typeof import('vue')['getCurrentInstance']
  const getCurrentScope: typeof import('vue')['getCurrentScope']
  const h: typeof import('vue')['h']
  const inject: typeof import('vue')['inject']
  const inputIdInjectionKey: typeof import('../src/runtime/composables/useFormField')['inputIdInjectionKey']
  const isProxy: typeof import('vue')['isProxy']
  const isReactive: typeof import('vue')['isReactive']
  const isReadonly: typeof import('vue')['isReadonly']
  const isRef: typeof import('vue')['isRef']
  const kbdKeysMap: typeof import('../src/runtime/composables/useKbd')['kbdKeysMap']
  const localeContextInjectionKey: typeof import('../src/runtime/composables/useLocale')['localeContextInjectionKey']
  const markRaw: typeof import('vue')['markRaw']
  const nextTick: typeof import('vue')['nextTick']
  const onActivated: typeof import('vue')['onActivated']
  const onBeforeMount: typeof import('vue')['onBeforeMount']
  const onBeforeUnmount: typeof import('vue')['onBeforeUnmount']
  const onBeforeUpdate: typeof import('vue')['onBeforeUpdate']
  const onDeactivated: typeof import('vue')['onDeactivated']
  const onErrorCaptured: typeof import('vue')['onErrorCaptured']
  const onMounted: typeof import('vue')['onMounted']
  const onRenderTracked: typeof import('vue')['onRenderTracked']
  const onRenderTriggered: typeof import('vue')['onRenderTriggered']
  const onScopeDispose: typeof import('vue')['onScopeDispose']
  const onServerPrefetch: typeof import('vue')['onServerPrefetch']
  const onUnmounted: typeof import('vue')['onUnmounted']
  const onUpdated: typeof import('vue')['onUpdated']
  const onWatcherCleanup: typeof import('vue')['onWatcherCleanup']
  const portalTargetInjectionKey: typeof import('../src/runtime/composables/usePortal')['portalTargetInjectionKey']
  const provide: typeof import('vue')['provide']
  const reactive: typeof import('vue')['reactive']
  const readonly: typeof import('vue')['readonly']
  const ref: typeof import('vue')['ref']
  const resolveComponent: typeof import('vue')['resolveComponent']
  const shallowReactive: typeof import('vue')['shallowReactive']
  const shallowReadonly: typeof import('vue')['shallowReadonly']
  const shallowRef: typeof import('vue')['shallowRef']
  const toRaw: typeof import('vue')['toRaw']
  const toRef: typeof import('vue')['toRef']
  const toRefs: typeof import('vue')['toRefs']
  const toValue: typeof import('vue')['toValue']
  const triggerRef: typeof import('vue')['triggerRef']
  const unref: typeof import('vue')['unref']
  const useAppConfig: typeof import('../src/runtime/vue/composables/useAppConfig')['useAppConfig']
  const useAttrs: typeof import('vue')['useAttrs']
  const useAvatarGroup: typeof import('../src/runtime/composables/useAvatarGroup')['useAvatarGroup']
  const useButtonGroup: typeof import('../src/runtime/composables/useButtonGroup')['useButtonGroup']
  const useComponentIcons: typeof import('../src/runtime/composables/useComponentIcons')['useComponentIcons']
  const useCssModule: typeof import('vue')['useCssModule']
  const useCssVars: typeof import('vue')['useCssVars']
  const useFormField: typeof import('../src/runtime/composables/useFormField')['useFormField']
  const useId: typeof import('vue')['useId']
  const useKbd: typeof import('../src/runtime/composables/useKbd')['useKbd']
  const useLocale: typeof import('../src/runtime/composables/useLocale')['useLocale']
  const useModel: typeof import('vue')['useModel']
  const useOverlay: typeof import('../src/runtime/composables/useOverlay')['useOverlay']
  const usePortal: typeof import('../src/runtime/composables/usePortal')['usePortal']
  const useSlots: typeof import('vue')['useSlots']
  const useTemplateRef: typeof import('vue')['useTemplateRef']
  const useToast: typeof import('../src/runtime/composables/useToast')['useToast']
  const watch: typeof import('vue')['watch']
  const watchEffect: typeof import('vue')['watchEffect']
  const watchPostEffect: typeof import('vue')['watchPostEffect']
  const watchSyncEffect: typeof import('vue')['watchSyncEffect']
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Component, ComponentPublicInstance, ComputedRef, DirectiveBinding, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, MaybeRef, MaybeRefOrGetter, VNode, WritableComputedRef } from 'vue'
  import('vue')
  // @ts-ignore
  export type { ShortcutConfig, ShortcutsConfig, ShortcutsOptions } from '../src/runtime/composables/defineShortcuts'
  import('../src/runtime/composables/defineShortcuts')
  // @ts-ignore
  export type { UseComponentIconsProps } from '../src/runtime/composables/useComponentIcons'
  import('../src/runtime/composables/useComponentIcons')
  // @ts-ignore
  export type { KbdKey, KbdKeySpecific } from '../src/runtime/composables/useKbd'
  import('../src/runtime/composables/useKbd')
  // @ts-ignore
  export type { OverlayOptions, Overlay } from '../src/runtime/composables/useOverlay'
  import('../src/runtime/composables/useOverlay')
  // @ts-ignore
  export type { Toast } from '../src/runtime/composables/useToast'
  import('../src/runtime/composables/useToast')
}
