import colors from 'tailwindcss/colors'
import type { ColorAlias, Shade, ThemeDoc } from './types'
import { DEFAULT_COLORS } from './types'

export type ColorMode = 'light' | 'dark'

/**
 * The semantic token defaults as @nuxt/ui ships them (src/runtime/index.css).
 * Exports diff against THESE — the docs site's own baseline diverges (e.g.
 * its light `--ui-bg` follows the neutral ramp), but an exported theme must
 * reproduce the preview on top of a stock library install.
 */
export const LIBRARY_TOKEN_DEFAULTS = {
  light: {
    // generated by the runtime colors plugin, not index.css
    '--ui-primary': 'var(--ui-color-primary-500)',
    '--ui-text-dimmed': 'var(--ui-color-neutral-400)',
    '--ui-text-muted': 'var(--ui-color-neutral-500)',
    '--ui-text-toned': 'var(--ui-color-neutral-600)',
    '--ui-text': 'var(--ui-color-neutral-700)',
    '--ui-text-highlighted': 'var(--ui-color-neutral-900)',
    '--ui-text-inverted': 'white',
    '--ui-bg': 'white',
    '--ui-bg-muted': 'var(--ui-color-neutral-50)',
    '--ui-bg-elevated': 'var(--ui-color-neutral-100)',
    '--ui-bg-accented': 'var(--ui-color-neutral-200)',
    '--ui-bg-inverted': 'var(--ui-color-neutral-900)',
    '--ui-border': 'var(--ui-color-neutral-200)',
    '--ui-border-muted': 'var(--ui-color-neutral-200)',
    '--ui-border-accented': 'var(--ui-color-neutral-300)',
    '--ui-border-inverted': 'var(--ui-color-neutral-900)'
  },
  dark: {
    '--ui-primary': 'var(--ui-color-primary-400)',
    '--ui-text-dimmed': 'var(--ui-color-neutral-500)',
    '--ui-text-muted': 'var(--ui-color-neutral-400)',
    '--ui-text-toned': 'var(--ui-color-neutral-300)',
    '--ui-text': 'var(--ui-color-neutral-200)',
    '--ui-text-highlighted': 'white',
    '--ui-text-inverted': 'var(--ui-color-neutral-900)',
    '--ui-bg': 'var(--ui-color-neutral-900)',
    '--ui-bg-muted': 'var(--ui-color-neutral-800)',
    '--ui-bg-elevated': 'var(--ui-color-neutral-800)',
    '--ui-bg-accented': 'var(--ui-color-neutral-700)',
    '--ui-bg-inverted': 'white',
    '--ui-border': 'var(--ui-color-neutral-800)',
    '--ui-border-muted': 'var(--ui-color-neutral-700)',
    '--ui-border-accented': 'var(--ui-color-neutral-700)',
    '--ui-border-inverted': 'white'
  }
} as const

export interface ResolvedToken {
  token: string
  /** The declared value at this level (`var(--ui-color-neutral-200)`, `white`, `#fff`…) */
  raw: string
  /** The final computed color when the chain resolves to one, otherwise the last known reference */
  value: string
  source: 'default' | 'override'
  /**
   * Inheritance breadcrumb, outermost first, e.g.
   * `['--ui-border', '--ui-color-neutral-200', '--color-slate-200', 'oklch(92.9% 0.013 255.508)']`
   */
  chain: string[]
}

const UI_COLOR_RE = /^var\(--ui-color-([a-z]+)-(\d{2,3})\)$/

/** Parse a `var(--ui-color-<alias>-<shade>)` reference, the one format the studio emits. */
export function parseUiColorRef(value?: string): { alias: string, shade: number } | undefined {
  const match = value?.match(UI_COLOR_RE)
  return match ? { alias: match[1]!, shade: Number(match[2]) } : undefined
}

export function resolveAlias(doc: ThemeDoc, alias: ColorAlias): string {
  return doc.colors?.[alias] || DEFAULT_COLORS[alias]
}

/** Color of a palette shade: custom palette first, then its base, then tailwind. */
export function resolveShade(doc: ThemeDoc, palette: string, shade: Shade): string | undefined {
  const custom = doc.palettes?.[palette]
  if (custom) {
    const value = custom.shades[shade]
    if (value) return value
    if (custom.extends) return resolveShade(doc, custom.extends, shade)
    return undefined
  }
  const tailwind = (colors as Record<string, unknown>)[palette]
  if (tailwind && typeof tailwind === 'object') {
    return (tailwind as Record<string, string>)[shade]
  }
  return undefined
}

export function resolveToken(doc: ThemeDoc, mode: ColorMode, token: string): ResolvedToken {
  const defaults = LIBRARY_TOKEN_DEFAULTS[mode] as Record<string, string>
  const override = doc.tokens?.[mode]?.[token]
  const raw = override ?? defaults[token] ?? ''

  const chain = [token]
  let value = raw

  const match = raw.match(UI_COLOR_RE)
  if (match) {
    const [, alias, shade] = match
    chain.push(`--ui-color-${alias}-${shade}`)

    const palette = resolveAlias(doc, alias as ColorAlias)
    chain.push(`--color-${palette}-${shade}`)

    const color = resolveShade(doc, palette, Number(shade) as Shade)
    if (color) {
      chain.push(color)
      value = color
    }
  } else if (raw) {
    chain.push(raw)
  }

  return {
    token,
    raw,
    value,
    source: override !== undefined ? 'override' : 'default',
    chain
  }
}

/** Resolve every semantic token for a mode, with provenance. */
export function resolveTokens(doc: ThemeDoc, mode: ColorMode): Record<string, ResolvedToken> {
  const defaults = LIBRARY_TOKEN_DEFAULTS[mode] as Record<string, string>
  const tokens = new Set([...Object.keys(defaults), ...Object.keys(doc.tokens?.[mode] || {})])

  return Object.fromEntries([...tokens].map(token => [token, resolveToken(doc, mode, token)]))
}
