import colors from 'tailwindcss/colors'
import type { ColorAlias, Shade, ThemeDoc } from './types'
import { DEFAULT_COLORS } from './types'

/**
 * The semantic token defaults as @nuxt/ui ships them (src/runtime/index.css).
 * Exports diff against THESE — the docs site's own baseline diverges (e.g.
 * its light `--ui-bg` follows the neutral ramp), but an exported theme must
 * reproduce the preview on top of a stock library install.
 */
export const LIBRARY_TOKEN_DEFAULTS = {
  light: {
    // the --ui-<alias> tokens are generated by the runtime colors plugin, not index.css
    '--ui-primary': 'var(--ui-color-primary-500)',
    '--ui-secondary': 'var(--ui-color-secondary-500)',
    '--ui-success': 'var(--ui-color-success-500)',
    '--ui-info': 'var(--ui-color-info-500)',
    '--ui-warning': 'var(--ui-color-warning-500)',
    '--ui-error': 'var(--ui-color-error-500)',
    '--ui-text-dimmed': 'var(--ui-color-neutral-400)',
    '--ui-text-muted': 'var(--ui-color-neutral-500)',
    '--ui-text-toned': 'var(--ui-color-neutral-600)',
    '--ui-text': 'var(--ui-color-neutral-700)',
    '--ui-text-highlighted': 'var(--ui-color-neutral-900)',
    '--ui-text-inverted': 'white',
    '--ui-bg': 'white',
    '--ui-bg-muted': 'var(--ui-color-neutral-50)',
    '--ui-bg-elevated': 'var(--ui-color-neutral-100)',
    '--ui-bg-accented': 'var(--ui-color-neutral-200)',
    '--ui-bg-inverted': 'var(--ui-color-neutral-900)',
    '--ui-border': 'var(--ui-color-neutral-200)',
    '--ui-border-muted': 'var(--ui-color-neutral-200)',
    '--ui-border-accented': 'var(--ui-color-neutral-300)',
    '--ui-border-inverted': 'var(--ui-color-neutral-900)'
  },
  dark: {
    '--ui-primary': 'var(--ui-color-primary-400)',
    '--ui-secondary': 'var(--ui-color-secondary-400)',
    '--ui-success': 'var(--ui-color-success-400)',
    '--ui-info': 'var(--ui-color-info-400)',
    '--ui-warning': 'var(--ui-color-warning-400)',
    '--ui-error': 'var(--ui-color-error-400)',
    '--ui-text-dimmed': 'var(--ui-color-neutral-500)',
    '--ui-text-muted': 'var(--ui-color-neutral-400)',
    '--ui-text-toned': 'var(--ui-color-neutral-300)',
    '--ui-text': 'var(--ui-color-neutral-200)',
    '--ui-text-highlighted': 'white',
    '--ui-text-inverted': 'var(--ui-color-neutral-900)',
    '--ui-bg': 'var(--ui-color-neutral-900)',
    '--ui-bg-muted': 'var(--ui-color-neutral-800)',
    '--ui-bg-elevated': 'var(--ui-color-neutral-800)',
    '--ui-bg-accented': 'var(--ui-color-neutral-700)',
    '--ui-bg-inverted': 'white',
    '--ui-border': 'var(--ui-color-neutral-800)',
    '--ui-border-muted': 'var(--ui-color-neutral-700)',
    '--ui-border-accented': 'var(--ui-color-neutral-700)',
    '--ui-border-inverted': 'white'
  }
} as const

// Standard stops ride the `--ui-color-<alias>-<shade>` indirection; the
// 100-step midpoints (150…850) have none — the runtime colours plugin only
// generates the 11 standard stops — so shadeRef emits them against the custom
// ramp's `--color-custom-<alias>-<mid>` variable instead. Both forms name the
// same ramp in the same capture position, so a single alternation parses both
// and midpoints promote back to governed shades exactly like standard stops.
const UI_COLOR_RE = /^var\(--(?:ui-color|color-custom)-([a-z]+)-(\d{2,3})\)$/

/**
 * Parse a shade reference the studio emits — both the standard-stop
 * `var(--ui-color-<alias>-<shade>)` form and the midpoint
 * `var(--color-custom-<alias>-<mid>)` form — to `{ alias, shade }`. The alias
 * is the ramp name in either case; callers apply their own ownership check
 * against it, so a ref on a foreign ramp is parsed but not adopted.
 */
export function parseUiColorRef(value?: string): { alias: string, shade: number } | undefined {
  const match = value?.match(UI_COLOR_RE)
  return match ? { alias: match[1]!, shade: Number(match[2]) } : undefined
}

export function resolveAlias(doc: ThemeDoc, alias: ColorAlias): string {
  return doc.colors?.[alias] || DEFAULT_COLORS[alias]
}

/** Color of a palette shade: custom palette first, then its base, then tailwind. */
export function resolveShade(doc: ThemeDoc, palette: string, shade: Shade): string | undefined {
  const custom = doc.palettes?.[palette]
  if (custom) {
    return custom.shades[shade]
  }
  const tailwind = (colors as Record<string, unknown>)[palette]
  if (tailwind && typeof tailwind === 'object') {
    return (tailwind as Record<string, string>)[shade]
  }
  return undefined
}
