import { simulateReadableStream } from 'ai'

export default defineEventHandler(async () => {
  return new Response(
    simulateReadableStream({
      initialDelayInMs: 500,
      chunkDelayInMs: 80,
      chunks: [
        `data: {"type":"start","messageId":"msg-${Date.now()}"}\n\n`,
        `data: {"type":"reasoning-start","id":"reasoning-1"}\n\n`,
        `data: {"type":"reasoning-delta","id":"reasoning-1","delta":"Let me "}\n\n`,
        `data: {"type":"reasoning-delta","id":"reasoning-1","delta":"think about "}\n\n`,
        `data: {"type":"reasoning-delta","id":"reasoning-1","delta":"this carefully...\\n\\n"}\n\n`,
        `data: {"type":"reasoning-delta","id":"reasoning-1","delta":"The user "}\n\n`,
        `data: {"type":"reasoning-delta","id":"reasoning-1","delta":"is asking "}\n\n`,
        `data: {"type":"reasoning-delta","id":"reasoning-1","delta":"a question "}\n\n`,
        `data: {"type":"reasoning-delta","id":"reasoning-1","delta":"that requires "}\n\n`,
        `data: {"type":"reasoning-delta","id":"reasoning-1","delta":"some context. "}\n\n`,
        `data: {"type":"reasoning-delta","id":"reasoning-1","delta":"I should first "}\n\n`,
        `data: {"type":"reasoning-delta","id":"reasoning-1","delta":"understand what "}\n\n`,
        `data: {"type":"reasoning-delta","id":"reasoning-1","delta":"they're looking for, "}\n\n`,
        `data: {"type":"reasoning-delta","id":"reasoning-1","delta":"then provide "}\n\n`,
        `data: {"type":"reasoning-delta","id":"reasoning-1","delta":"a clear explanation.\\n\\n"}\n\n`,
        `data: {"type":"reasoning-delta","id":"reasoning-1","delta":"I'll need to "}\n\n`,
        `data: {"type":"reasoning-delta","id":"reasoning-1","delta":"consider the "}\n\n`,
        `data: {"type":"reasoning-delta","id":"reasoning-1","delta":"technical aspects "}\n\n`,
        `data: {"type":"reasoning-delta","id":"reasoning-1","delta":"while keeping "}\n\n`,
        `data: {"type":"reasoning-delta","id":"reasoning-1","delta":"it accessible. "}\n\n`,
        `data: {"type":"reasoning-delta","id":"reasoning-1","delta":"Maybe I should "}\n\n`,
        `data: {"type":"reasoning-delta","id":"reasoning-1","delta":"include some "}\n\n`,
        `data: {"type":"reasoning-delta","id":"reasoning-1","delta":"examples to "}\n\n`,
        `data: {"type":"reasoning-delta","id":"reasoning-1","delta":"make it clearer.\\n\\n"}\n\n`,
        `data: {"type":"reasoning-delta","id":"reasoning-1","delta":"Ok, I think "}\n\n`,
        `data: {"type":"reasoning-delta","id":"reasoning-1","delta":"I have a good "}\n\n`,
        `data: {"type":"reasoning-delta","id":"reasoning-1","delta":"approach now."}\n\n`,
        `data: {"type":"reasoning-end","id":"reasoning-1"}\n\n`,
        `data: {"type":"text-start","id":"text-1"}\n\n`,
        `data: {"type":"text-delta","id":"text-1","delta":"## Simulated "}\n\n`,
        `data: {"type":"text-delta","id":"text-1","delta":"Streaming Response\\n\\n"}\n\n`,
        `data: {"type":"text-delta","id":"text-1","delta":"This is a "}\n\n`,
        `data: {"type":"text-delta","id":"text-1","delta":"**simulated** streaming "}\n\n`,
        `data: {"type":"text-delta","id":"text-1","delta":"response using "}\n\n`,
        `data: {"type":"text-delta","id":"text-1","delta":"the AI SDK's "}\n\n`,
        `data: {"type":"text-delta","id":"text-1","delta":"\`simulateReadableStream\` "}\n\n`,
        `data: {"type":"text-delta","id":"text-1","delta":"utility.\\n\\n"}\n\n`,
        `data: {"type":"text-delta","id":"text-1","delta":"## Features "}\n\n`,
        `data: {"type":"text-delta","id":"text-1","delta":"Demonstrated\\n\\n"}\n\n`,
        `data: {"type":"text-delta","id":"text-1","delta":"1. **Reasoning blocks** "}\n\n`,
        `data: {"type":"text-delta","id":"text-1","delta":"- Shows the AI's "}\n\n`,
        `data: {"type":"text-delta","id":"text-1","delta":"thinking process\\n"}\n\n`,
        `data: {"type":"text-delta","id":"text-1","delta":"2. **Text streaming** "}\n\n`,
        `data: {"type":"text-delta","id":"text-1","delta":"- Progressive content "}\n\n`,
        `data: {"type":"text-delta","id":"text-1","delta":"delivery\\n"}\n\n`,
        `data: {"type":"text-delta","id":"text-1","delta":"3. **Markdown rendering** "}\n\n`,
        `data: {"type":"text-delta","id":"text-1","delta":"- Rich text formatting\\n\\n"}\n\n`,
        `data: {"type":"text-delta","id":"text-1","delta":"## Code Example\\n\\n"}\n\n`,
        `data: {"type":"text-delta","id":"text-1","delta":"\`\`\`typescript\\n"}\n\n`,
        `data: {"type":"text-delta","id":"text-1","delta":"const response = "}\n\n`,
        `data: {"type":"text-delta","id":"text-1","delta":"await chat"}\n\n`,
        `data: {"type":"text-delta","id":"text-1","delta":".sendMessage("}\n\n`,
        `data: {"type":"text-delta","id":"text-1","delta":"{ text: 'Hello!' })"}\n\n`,
        `data: {"type":"text-delta","id":"text-1","delta":"\\n\`\`\`\\n\\n"}\n\n`,
        `data: {"type":"text-delta","id":"text-1","delta":"> **Note:** This "}\n\n`,
        `data: {"type":"text-delta","id":"text-1","delta":"is a mock response "}\n\n`,
        `data: {"type":"text-delta","id":"text-1","delta":"for testing purposes."}\n\n`,
        `data: {"type":"text-end","id":"text-1"}\n\n`,
        `data: {"type":"finish"}\n\n`,
        `data: [DONE]\n\n`
      ]
    }).pipeThrough(new TextEncoderStream()),
    {
      status: 200,
      headers: {
        'Content-Type': 'text/event-stream',
        'Cache-Control': 'no-cache',
        'Connection': 'keep-alive',
        'x-vercel-ai-ui-message-stream': 'v1'
      }
    }
  )
})
