name: reproduire

on:
  issues:
    types: [labeled]

permissions:
  issues: write

jobs:
  reproduire:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: Hebilicious/reproduire@a4b274773e3d6e8bef547385710473af11f5ec5d # v0.0.9-mp
        with:
          label: needs reproduction