name: reproduire

on:
  issues:
    types: [labeled]

permissions:
  issues: write

jobs:
  reproduire:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: Hebilicious/reproduire@4b686ae9cbb72dad60f001d278b6e3b2ce40a9ac # v0.0.9
        with:
          label: needs reproduction