name: reproduction

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'

jobs:
  reproduction:
    runs-on: ubuntu-latest

    permissions:
      actions: write
      issues: write

    steps:
      - uses: actions/stale@v10
        with:
          days-before-stale: -1
          stale-issue-label: 'needs reproduction'
          only-labels: 'needs reproduction'
          days-before-issue-close: 7
          ignore-updates: true
          remove-stale-when-updated: false
          close-issue-message: |
            Hi! 👋 This issue was closed because it was open for 7 days without a reproduction.
          close-issue-label: 'closed-by-bot'
          operations-per-run: 300
